// LAST PATCHED ON 19th Oct 2024
export interface Champion {
  id: string;
  title: string;
  gender: string;
  name: string;
  positions: string[];
  regions: string[];
  species: string[];
  releaseDate: string;
  resource: string;
  rangeTypes: string[];
}

export const ChampionData = [
  {
    id: 'Aatrox',
    title: 'the Darkin Blade',
    gender: 'Male',
    name: 'Aatrox',
    positions: ['Top'],
    regions: ['Runeterra', 'Shurima'],
    species: ['Darkin'],
    releaseDate: '2013-06-13',
    resource: 'Manaless',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Ahri',
    title: 'the Nine-Tailed Fox',
    gender: 'Female',
    name: 'Ahri',
    positions: ['Middle'],
    regions: ['Ionia'],
    species: ['Vastayan'],
    releaseDate: '2011-12-14',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Akali',
    title: 'the Rogue Assassin',
    gender: 'Female',
    name: 'Akali',
    positions: ['Top', 'Middle'],
    regions: ['Ionia'],
    species: ['Human'],
    releaseDate: '2010-05-11',
    resource: 'Energy',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Akshan',
    title: 'the Rogue Sentinel',
    gender: 'Male',
    name: 'Akshan',
    positions: ['Middle'],
    regions: ['Shurima'],
    species: ['Human'],
    releaseDate: '2021-07-22',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Alistar',
    title: 'the Minotaur',
    gender: 'Male',
    name: 'Alistar',
    positions: ['Support'],
    regions: ['Runeterra'],
    species: ['Minotaur'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Ambessa',
    title: 'Matriarch of War',
    gender: 'Female',
    name: 'Ambessa',
    positions: ['Top', 'Jungle', 'Mid'],
    regions: ['Noxus', 'Piltover'],
    species: ['Human'],
    releaseDate: '2024-11-06',
    resource: 'Energy',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Amumu',
    title: 'the Sad Mummy',
    gender: 'Male',
    name: 'Amumu',
    positions: ['Jungle'],
    regions: ['Shurima'],
    species: ['Undead', 'Yordle'],
    releaseDate: '2009-06-26',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Anivia',
    title: 'the Cryophoenix',
    gender: 'Female',
    name: 'Anivia',
    positions: ['Middle'],
    regions: ['Freljord'],
    species: ['Spirit', 'God'],
    releaseDate: '2009-07-10',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Annie',
    title: 'the Dark Child',
    gender: 'Female',
    name: 'Annie',
    positions: ['Middle'],
    regions: ['Noxus', 'Runeterra'],
    species: ['Human', 'Magicborn'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Aphelios',
    title: 'the Weapon of the Faithful',
    gender: 'Male',
    name: 'Aphelios',
    positions: ['Bottom'],
    regions: ['Targon'],
    species: ['Human', 'Spiritualist'],
    releaseDate: '2019-12-11',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Ashe',
    title: 'the Frost Archer',
    gender: 'Female',
    name: 'Ashe',
    positions: ['Bottom'],
    regions: ['Freljord'],
    species: ['Human', 'Iceborn'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'AurelionSol',
    title: 'The Star Forger',
    gender: 'Male',
    name: 'Aurelion Sol',
    positions: ['Middle'],
    regions: ['Runeterra', 'Targon'],
    species: ['Celestial', 'Dragon'],
    releaseDate: '2016-03-24',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Aurora',
    title: 'the Witch Between Worlds',
    gender: 'Female',
    name: 'Aurora',
    positions: ['Middle'],
    regions: ['Freljord'],
    species: ['Vastayan'],
    releaseDate: '2024-07-17',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Azir',
    title: 'the Emperor of the Sands',
    gender: 'Male',
    name: 'Azir',
    positions: ['Middle'],
    regions: ['Shurima'],
    species: ['God-Warrior'],
    releaseDate: '2014-09-16',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Bard',
    title: 'the Wandering Caretaker',
    gender: 'Male',
    name: 'Bard',
    positions: ['Support'],
    regions: ['Runeterra'],
    species: ['Celestial'],
    releaseDate: '2015-03-12',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Belveth',
    title: 'the Empress of the Void',
    gender: 'Female',
    name: "Bel'Veth",
    positions: ['Jungle'],
    regions: ['Void'],
    species: ['Void-Being'],
    releaseDate: '2022-06-09',
    resource: 'Manaless',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Blitzcrank',
    title: 'the Great Steam Golem',
    gender: 'Other',
    name: 'Blitzcrank',
    positions: ['Support'],
    regions: ['Zaun'],
    species: ['Golem'],
    releaseDate: '2009-09-02',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Brand',
    title: 'the Burning Vengeance',
    gender: 'Male',
    name: 'Brand',
    positions: ['Jungle', 'Middle', 'Support'],
    regions: ['Freljord', 'Runeterra'],
    species: ['Human', 'Magically Altered'],
    releaseDate: '2011-04-12',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Braum',
    title: 'the Heart of the Freljord',
    gender: 'Male',
    name: 'Braum',
    positions: ['Support'],
    regions: ['Freljord'],
    species: ['Human', 'Iceborn'],
    releaseDate: '2014-05-12',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Briar',
    title: 'the Restrained Hunger',
    gender: 'Female',
    name: 'Briar',
    positions: ['Jungle'],
    regions: ['Noxus'],
    species: ['Golem'],
    releaseDate: '2023-09-14',
    resource: 'Health costs',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Caitlyn',
    title: 'the Sheriff of Piltover',
    gender: 'Female',
    name: 'Caitlyn',
    positions: ['Bottom'],
    regions: ['Piltover'],
    species: ['Human'],
    releaseDate: '2011-01-04',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Camille',
    title: 'the Steel Shadow',
    gender: 'Female',
    name: 'Camille',
    positions: ['Top'],
    regions: ['Piltover'],
    species: ['Human', 'Cyborg'],
    releaseDate: '2016-12-07',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Cassiopeia',
    title: "the Serpent's Embrace",
    gender: 'Female',
    name: 'Cassiopeia',
    positions: ['Top', 'Middle'],
    regions: ['Noxus', 'Shurima'],
    species: ['Human', 'Magically Altered'],
    releaseDate: '2010-12-14',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Chogath',
    title: 'the Terror of the Void',
    gender: 'Male',
    name: "Cho'Gath",
    positions: ['Top'],
    regions: ['Void'],
    species: ['Void-Being'],
    releaseDate: '2009-06-26',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Corki',
    title: 'the Daring Bombardier',
    gender: 'Male',
    name: 'Corki',
    positions: ['Middle'],
    regions: ['Bandle City', 'Piltover'],
    species: ['Yordle'],
    releaseDate: '2009-09-19',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Darius',
    title: 'the Hand of Noxus',
    gender: 'Male',
    name: 'Darius',
    positions: ['Top'],
    regions: ['Noxus'],
    species: ['Human'],
    releaseDate: '2012-05-23',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Diana',
    title: 'Scorn of the Moon',
    gender: 'Female',
    name: 'Diana',
    positions: ['Jungle', 'Middle'],
    regions: ['Targon'],
    species: ['Human', 'Aspect'],
    releaseDate: '2012-08-07',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Draven',
    title: 'the Glorious Executioner',
    gender: 'Male',
    name: 'Draven',
    positions: ['Bottom'],
    regions: ['Noxus'],
    species: ['Human'],
    releaseDate: '2012-06-06',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'DrMundo',
    title: 'the Madman of Zaun',
    gender: 'Male',
    name: 'Dr. Mundo',
    positions: ['Top'],
    regions: ['Zaun'],
    species: ['Human', 'Chemically Altered'],
    releaseDate: '2009-09-02',
    resource: 'Health costs',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Ekko',
    title: 'the Boy Who Shattered Time',
    gender: 'Male',
    name: 'Ekko',
    positions: ['Jungle', 'Middle'],
    regions: ['Zaun'],
    species: ['Human'],
    releaseDate: '2015-05-29',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Elise',
    title: 'the Spider Queen',
    gender: 'Female',
    name: 'Elise',
    positions: ['Jungle'],
    regions: ['Shadow Isles', 'Noxus'],
    species: ['Human', 'Magically Altered'],
    releaseDate: '2012-10-26',
    resource: 'Mana',
    rangeTypes: ['Melee', 'Ranged'],
  },
  {
    id: 'Evelynn',
    title: "Agony's Embrace",
    gender: 'Female',
    name: 'Evelynn',
    positions: ['Jungle'],
    regions: ['Runeterra'],
    species: ['Demon', 'Spirit'],
    releaseDate: '2009-05-01',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Ezreal',
    title: 'the Prodigal Explorer',
    gender: 'Male',
    name: 'Ezreal',
    positions: ['Bottom'],
    regions: ['Piltover'],
    species: ['Human', 'Magicborn'],
    releaseDate: '2010-03-16',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Fiddlesticks',
    title: 'the Ancient Fear',
    gender: 'Other',
    name: 'Fiddlesticks',
    positions: ['Jungle'],
    regions: ['Runeterra'],
    species: ['Demon', 'Spirit'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Fiora',
    title: 'the Grand Duelist',
    gender: 'Female',
    name: 'Fiora',
    positions: ['Top'],
    regions: ['Demacia'],
    species: ['Human'],
    releaseDate: '2012-02-29',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Fizz',
    title: 'the Tidal Trickster',
    gender: 'Male',
    name: 'Fizz',
    positions: ['Middle'],
    regions: ['Bilgewater'],
    species: ['Yordle'],
    releaseDate: '2011-11-15',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Galio',
    title: 'the Colossus',
    gender: 'Male',
    name: 'Galio',
    positions: ['Middle'],
    regions: ['Demacia'],
    species: ['Golem'],
    releaseDate: '2010-08-10',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Gangplank',
    title: 'the Saltwater Scourge',
    gender: 'Male',
    name: 'Gangplank',
    positions: ['Top'],
    regions: ['Bilgewater'],
    species: ['Human'],
    releaseDate: '2009-08-19',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Garen',
    title: 'The Might of Demacia',
    gender: 'Male',
    name: 'Garen',
    positions: ['Top'],
    regions: ['Demacia'],
    species: ['Human'],
    releaseDate: '2010-04-27',
    resource: 'Manaless',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Gnar',
    title: 'the Missing Link',
    gender: 'Male',
    name: 'Gnar',
    positions: ['Top'],
    regions: ['Freljord'],
    species: ['Yordle'],
    releaseDate: '2014-08-14',
    resource: 'Rage',
    rangeTypes: ['Melee', 'Ranged'],
  },
  {
    id: 'Gragas',
    title: 'the Rabble Rouser',
    gender: 'Male',
    name: 'Gragas',
    positions: ['Top', 'Jungle'],
    regions: ['Freljord'],
    species: ['Human', 'Iceborn'],
    releaseDate: '2010-02-02',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Graves',
    title: 'the Outlaw',
    gender: 'Male',
    name: 'Graves',
    positions: ['Jungle'],
    regions: ['Bilgewater'],
    species: ['Human'],
    releaseDate: '2011-10-19',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Gwen',
    title: 'The Hallowed Seamstress',
    gender: 'Female',
    name: 'Gwen',
    positions: ['Top'],
    regions: ['Shadow Isles', 'Camavor'],
    species: ['Human', 'Magically Altered'],
    releaseDate: '2021-04-15',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Hecarim',
    title: 'the Shadow of War',
    gender: 'Male',
    name: 'Hecarim',
    positions: ['Jungle'],
    regions: ['Shadow Isles', 'Camavor'],
    species: ['Undead'],
    releaseDate: '2012-04-18',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Heimerdinger',
    title: 'the Revered Inventor',
    gender: 'Male',
    name: 'Heimerdinger',
    positions: ['Top', 'Middle'],
    regions: ['Piltover'],
    species: ['Yordle'],
    releaseDate: '2009-10-10',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Hwei',
    title: 'the Visionary',
    gender: 'Male',
    name: 'Hwei',
    positions: ['Middle', 'Support'],
    regions: ['Ionia'],
    species: ['Human', 'Magicborn'],
    releaseDate: '2023-12-05',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Illaoi',
    title: 'the Kraken Priestess',
    gender: 'Female',
    name: 'Illaoi',
    positions: ['Top'],
    regions: ['Bilgewater'],
    species: ['Human', 'Spiritualist'],
    releaseDate: '2015-11-24',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Irelia',
    title: 'the Blade Dancer',
    gender: 'Female',
    name: 'Irelia',
    positions: ['Top', 'Middle'],
    regions: ['Ionia'],
    species: ['Human', 'Spiritualist'],
    releaseDate: '2010-11-16',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Ivern',
    title: 'the Green Father',
    gender: 'Male',
    name: 'Ivern',
    positions: ['Jungle'],
    regions: ['Ionia', 'Freljord'],
    species: ['Human', 'Magically Altered'],
    releaseDate: '2016-10-05',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Janna',
    title: "the Storm's Fury",
    gender: 'Female',
    name: 'Janna',
    positions: ['Support'],
    regions: ['Zaun', 'Shurima'],
    species: ['Spirit', 'God'],
    releaseDate: '2009-09-02',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'JarvanIV',
    title: 'the Exemplar of Demacia',
    gender: 'Male',
    name: 'Jarvan IV',
    positions: ['Jungle'],
    regions: ['Demacia'],
    species: ['Human'],
    releaseDate: '2011-03-01',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Jax',
    title: 'Grandmaster at Arms',
    gender: 'Male',
    name: 'Jax',
    positions: ['Top', 'Jungle'],
    regions: ['Runeterra', 'Icathia', 'Shurima'],
    species: ['Unknown'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Jayce',
    title: 'the Defender of Tomorrow',
    gender: 'Male',
    name: 'Jayce',
    positions: ['Top', 'Middle'],
    regions: ['Piltover'],
    species: ['Human'],
    releaseDate: '2012-07-07',
    resource: 'Mana',
    rangeTypes: ['Melee', 'Ranged'],
  },
  {
    id: 'Jhin',
    title: 'the Virtuoso',
    gender: 'Male',
    name: 'Jhin',
    positions: ['Bottom'],
    regions: ['Ionia'],
    species: ['Human', 'Spiritualist'],
    releaseDate: '2016-02-01',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Jinx',
    title: 'the Loose Cannon',
    gender: 'Female',
    name: 'Jinx',
    positions: ['Bottom'],
    regions: ['Zaun'],
    species: ['Human', 'Chemically Altered'],
    releaseDate: '2013-10-10',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Kaisa',
    title: 'Daughter of the Void',
    gender: 'Female',
    name: "Kai'Sa",
    positions: ['Bottom'],
    regions: ['Shurima', 'Void'],
    species: ['Human', 'Void-Being'],
    releaseDate: '2018-03-07',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Kalista',
    title: 'the Spear of Vengeance',
    gender: 'Female',
    name: 'Kalista',
    positions: ['Bottom'],
    regions: ['Shadow Isles', 'Camavor'],
    species: ['Undead'],
    releaseDate: '2014-11-20',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Karma',
    title: 'the Enlightened One',
    gender: 'Female',
    name: 'Karma',
    positions: ['Support'],
    regions: ['Ionia'],
    species: ['Human', 'Spiritualist'],
    releaseDate: '2011-02-01',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Karthus',
    title: 'the Deathsinger',
    gender: 'Male',
    name: 'Karthus',
    positions: ['Jungle'],
    regions: ['Shadow Isles', 'Noxus'],
    species: ['Undead'],
    releaseDate: '2009-06-12',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Kassadin',
    title: 'the Void Walker',
    gender: 'Male',
    name: 'Kassadin',
    positions: ['Middle'],
    regions: ['Shurima', 'Void'],
    species: ['Human', 'Void-Being'],
    releaseDate: '2009-08-07',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Katarina',
    title: 'the Sinister Blade',
    gender: 'Female',
    name: 'Katarina',
    positions: ['Middle'],
    regions: ['Noxus'],
    species: ['Human'],
    releaseDate: '2009-09-19',
    resource: 'Manaless',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Kayle',
    title: 'the Righteous',
    gender: 'Female',
    name: 'Kayle',
    positions: ['Top'],
    regions: ['Demacia', 'Targon'],
    species: ['Human', 'Magically Altered', 'Aspect'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Melee', 'Ranged'],
  },
  {
    id: 'Kayn',
    title: 'the Shadow Reaper',
    gender: 'Male',
    name: 'Kayn',
    positions: ['Jungle'],
    regions: ['Ionia', 'Runeterra', 'Noxus', 'Shurima'],
    species: ['Darkin', 'Human', 'Magically Altered'],
    releaseDate: '2017-07-12',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Kennen',
    title: 'the Heart of the Tempest',
    gender: 'Male',
    name: 'Kennen',
    positions: ['Top'],
    regions: ['Ionia'],
    species: ['Yordle'],
    releaseDate: '2010-04-08',
    resource: 'Energy',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Khazix',
    title: 'the Voidreaver',
    gender: 'Male',
    name: "Kha'Zix",
    positions: ['Jungle'],
    regions: ['Void'],
    species: ['Void-Being'],
    releaseDate: '2012-09-27',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Kindred',
    title: 'The Eternal Hunters',
    gender: 'Other',
    name: 'Kindred',
    positions: ['Jungle'],
    regions: ['Runeterra'],
    species: ['Spirit', 'God'],
    releaseDate: '2015-10-14',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Kled',
    title: 'the Cantankerous Cavalier',
    gender: 'Male',
    name: 'Kled',
    positions: ['Top'],
    regions: ['Noxus'],
    species: ['Yordle'],
    releaseDate: '2016-08-10',
    resource: 'Courage',
    rangeTypes: ['Melee'],
  },
  {
    id: 'KogMaw',
    title: 'the Mouth of the Abyss',
    gender: 'Male',
    name: "Kog'Maw",
    positions: ['Bottom'],
    regions: ['Void'],
    species: ['Void-Being'],
    releaseDate: '2010-06-24',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'KSante',
    title: 'the Pride of Nazumah',
    gender: 'Male',
    name: "K'Sante",
    positions: ['Top'],
    regions: ['Shurima'],
    species: ['Human'],
    releaseDate: '2022-11-02',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Leblanc',
    title: 'the Deceiver',
    gender: 'Female',
    name: 'LeBlanc',
    positions: ['Middle'],
    regions: ['Noxus'],
    species: ['Human', 'Magically Altered'],
    releaseDate: '2010-11-02',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'LeeSin',
    title: 'the Blind Monk',
    gender: 'Male',
    name: 'Lee Sin',
    positions: ['Jungle'],
    regions: ['Ionia'],
    species: ['Human', 'Spiritualist'],
    releaseDate: '2011-04-01',
    resource: 'Energy',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Leona',
    title: 'the Radiant Dawn',
    gender: 'Female',
    name: 'Leona',
    positions: ['Support'],
    regions: ['Targon'],
    species: ['Human', 'Aspect'],
    releaseDate: '2011-07-13',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Lillia',
    title: 'the Bashful Bloom',
    gender: 'Female',
    name: 'Lillia',
    positions: ['Jungle'],
    regions: ['Ionia'],
    species: ['Spirit'],
    releaseDate: '2020-07-22',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Lissandra',
    title: 'the Ice Witch',
    gender: 'Female',
    name: 'Lissandra',
    positions: ['Middle'],
    regions: ['Freljord'],
    species: ['Human', 'Iceborn'],
    releaseDate: '2013-04-30',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Lucian',
    title: 'the Purifier',
    gender: 'Male',
    name: 'Lucian',
    positions: ['Bottom'],
    regions: ['Demacia', 'Shadow Isles'],
    species: ['Human'],
    releaseDate: '2013-08-22',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Lulu',
    title: 'the Fae Sorceress',
    gender: 'Female',
    name: 'Lulu',
    positions: ['Support'],
    regions: ['Bandle City'],
    species: ['Yordle'],
    releaseDate: '2012-03-20',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Lux',
    title: 'the Lady of Luminosity',
    gender: 'Female',
    name: 'Lux',
    positions: ['Middle', 'Support'],
    regions: ['Demacia'],
    species: ['Human', 'Magicborn'],
    releaseDate: '2010-10-19',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Malphite',
    title: 'Shard of the Monolith',
    gender: 'Male',
    name: 'Malphite',
    positions: ['Top', 'Middle'],
    regions: ['Ixtal', 'Shurima'],
    species: ['Golem'],
    releaseDate: '2009-09-02',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Malzahar',
    title: 'the Prophet of the Void',
    gender: 'Male',
    name: 'Malzahar',
    positions: ['Middle'],
    regions: ['Shurima', 'Void'],
    species: ['Human', 'Void-Being'],
    releaseDate: '2010-06-01',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Maokai',
    title: 'the Twisted Treant',
    gender: 'Male',
    name: 'Maokai',
    positions: ['Jungle', 'Support'],
    regions: ['Shadow Isles'],
    species: ['Spirit'],
    releaseDate: '2011-02-16',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'MasterYi',
    title: 'the Wuju Bladesman',
    gender: 'Male',
    name: 'Master Yi',
    positions: ['Jungle'],
    regions: ['Ionia'],
    species: ['Human', 'Spiritualist'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Milio',
    title: 'The Gentle Flame',
    gender: 'Male',
    name: 'Milio',
    positions: ['Support'],
    regions: ['Ixtal'],
    species: ['Human', 'Magicborn'],
    releaseDate: '2023-03-23',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'MissFortune',
    title: 'the Bounty Hunter',
    gender: 'Female',
    name: 'Miss Fortune',
    positions: ['Bottom'],
    regions: ['Bilgewater'],
    species: ['Human'],
    releaseDate: '2010-09-08',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'MonkeyKing',
    title: 'the Monkey King',
    gender: 'Male',
    name: 'Wukong',
    positions: ['Top', 'Jungle'],
    regions: ['Ionia'],
    species: ['Vastayan'],
    releaseDate: '2011-07-26',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Mordekaiser',
    title: 'the Iron Revenant',
    gender: 'Male',
    name: 'Mordekaiser',
    positions: ['Top'],
    regions: ['Noxus', 'Shadow Isles'],
    species: ['Revenant'],
    releaseDate: '2010-02-24',
    resource: 'Shield',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Morgana',
    title: 'the Fallen',
    gender: 'Female',
    name: 'Morgana',
    positions: ['Support'],
    regions: ['Demacia', 'Targon'],
    species: ['Human', 'Magically Altered', 'Aspect'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Naafiri',
    title: 'the Hound of a Hundred Bites',
    gender: 'Female',
    name: 'Naafiri',
    positions: ['Middle'],
    regions: ['Shurima'],
    species: ['Dog', 'Darkin'],
    releaseDate: '2023-07-19',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Nami',
    title: 'the Tidecaller',
    gender: 'Female',
    name: 'Nami',
    positions: ['Support'],
    regions: ['Runeterra', 'Bilgewater'],
    species: ['Vastayan'],
    releaseDate: '2012-12-07',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Nasus',
    title: 'the Curator of the Sands',
    gender: 'Male',
    name: 'Nasus',
    positions: ['Top'],
    regions: ['Shurima'],
    species: ['God-Warrior'],
    releaseDate: '2009-10-01',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Nautilus',
    title: 'the Titan of the Depths',
    gender: 'Male',
    name: 'Nautilus',
    positions: ['Support'],
    regions: ['Bilgewater'],
    species: ['Revenant'],
    releaseDate: '2012-02-14',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Neeko',
    title: 'the Curious Chameleon',
    gender: 'Female',
    name: 'Neeko',
    positions: ['Middle', 'Support'],
    regions: ['Ixtal'],
    species: ['Vastayan'],
    releaseDate: '2018-12-05',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Nidalee',
    title: 'the Bestial Huntress',
    gender: 'Female',
    name: 'Nidalee',
    positions: ['Jungle'],
    regions: ['Ixtal'],
    species: ['Human', 'Spiritualist'],
    releaseDate: '2009-12-17',
    resource: 'Mana',
    rangeTypes: ['Melee', 'Ranged'],
  },
  {
    id: 'Nilah',
    title: 'the Joy Unbound',
    gender: 'Female',
    name: 'Nilah',
    positions: ['Bottom'],
    regions: ['Bilgewater'],
    species: ['Human', 'Magically Altered'],
    releaseDate: '2022-07-13',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Nocturne',
    title: 'the Eternal Nightmare',
    gender: 'Male',
    name: 'Nocturne',
    positions: ['Jungle'],
    regions: ['Runeterra'],
    species: ['Demon', 'Spirit'],
    releaseDate: '2011-03-15',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Nunu',
    title: 'the Boy and His Yeti',
    gender: 'Male',
    name: 'Nunu & Willump',
    positions: ['Jungle'],
    regions: ['Freljord'],
    species: ['Human', 'Yeti'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Olaf',
    title: 'the Berserker',
    gender: 'Male',
    name: 'Olaf',
    positions: ['Top'],
    regions: ['Freljord'],
    species: ['Human', 'Iceborn'],
    releaseDate: '2010-06-09',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Orianna',
    title: 'the Lady of Clockwork',
    gender: 'Female',
    name: 'Orianna',
    positions: ['Middle'],
    regions: ['Piltover'],
    species: ['Golem'],
    releaseDate: '2011-06-01',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Ornn',
    title: 'The Fire below the Mountain',
    gender: 'Male',
    name: 'Ornn',
    positions: ['Top'],
    regions: ['Freljord'],
    species: ['Spirit', 'God'],
    releaseDate: '2017-08-23',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Pantheon',
    title: 'the Unbreakable Spear',
    gender: 'Male',
    name: 'Pantheon',
    positions: ['Top', 'Support'],
    regions: ['Targon'],
    species: ['Human', 'Aspect'],
    releaseDate: '2010-02-02',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Poppy',
    title: 'Keeper of the Hammer',
    gender: 'Female',
    name: 'Poppy',
    positions: ['Top', 'Jungle', 'Support'],
    regions: ['Demacia'],
    species: ['Yordle'],
    releaseDate: '2010-01-13',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Pyke',
    title: 'the Bloodharbor Ripper',
    gender: 'Male',
    name: 'Pyke',
    positions: ['Support'],
    regions: ['Bilgewater'],
    species: ['Revenant'],
    releaseDate: '2018-05-31',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Qiyana',
    title: 'Empress of the Elements',
    gender: 'Female',
    name: 'Qiyana',
    positions: ['Middle'],
    regions: ['Ixtal'],
    species: ['Human', 'Magicborn'],
    releaseDate: '2019-06-28',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Quinn',
    title: "Demacia's Wings",
    gender: 'Female',
    name: 'Quinn',
    positions: ['Top', 'Middle'],
    regions: ['Demacia'],
    species: ['Human'],
    releaseDate: '2013-03-01',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Rakan',
    title: 'The Charmer',
    gender: 'Male',
    name: 'Rakan',
    positions: ['Support'],
    regions: ['Ionia'],
    species: ['Vastayan'],
    releaseDate: '2017-04-19',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Rammus',
    title: 'the Armordillo',
    gender: 'Male',
    name: 'Rammus',
    positions: ['Jungle'],
    regions: ['Shurima'],
    species: ['Unknown'],
    releaseDate: '2009-07-10',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'RekSai',
    title: 'the Void Burrower',
    gender: 'Female',
    name: "Rek'Sai",
    positions: ['Jungle'],
    regions: ['Shurima', 'Void'],
    species: ['Void-Being'],
    releaseDate: '2014-12-11',
    resource: 'Rage',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Rell',
    title: 'the Iron Maiden',
    gender: 'Female',
    name: 'Rell',
    positions: ['Support'],
    regions: ['Noxus'],
    species: ['Human', 'Magicborn', 'Magically Altered'],
    releaseDate: '2020-12-10',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Renata',
    title: 'the Chem-Baroness',
    gender: 'Female',
    name: 'Renata Glasc',
    positions: ['Support'],
    regions: ['Zaun'],
    species: ['Human', 'Chemically Altered'],
    releaseDate: '2022-02-17',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Renekton',
    title: 'the Butcher of the Sands',
    gender: 'Male',
    name: 'Renekton',
    positions: ['Top'],
    regions: ['Shurima'],
    species: ['God-Warrior'],
    releaseDate: '2011-01-18',
    resource: 'Fury',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Rengar',
    title: 'the Pridestalker',
    gender: 'Male',
    name: 'Rengar',
    positions: ['Jungle'],
    regions: ['Ixtal', 'Shurima'],
    species: ['Vastayan'],
    releaseDate: '2012-08-21',
    resource: 'Ferocity',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Riven',
    title: 'the Exile',
    gender: 'Female',
    name: 'Riven',
    positions: ['Top'],
    regions: ['Ionia', 'Noxus'],
    species: ['Human'],
    releaseDate: '2011-09-14',
    resource: 'Manaless',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Rumble',
    title: 'the Mechanized Menace',
    gender: 'Male',
    name: 'Rumble',
    positions: ['Top'],
    regions: ['Bandle City'],
    species: ['Yordle'],
    releaseDate: '2011-04-26',
    resource: 'Heat',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Ryze',
    title: 'the Rune Mage',
    gender: 'Male',
    name: 'Ryze',
    positions: ['Top', 'Middle'],
    regions: ['Runeterra'],
    species: ['Human', 'Magically Altered'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Samira',
    title: 'the Desert Rose',
    gender: 'Female',
    name: 'Samira',
    positions: ['Bottom'],
    regions: ['Shurima', 'Noxus'],
    species: ['Human'],
    releaseDate: '2020-09-21',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Sejuani',
    title: 'Fury of the North',
    gender: 'Female',
    name: 'Sejuani',
    positions: ['Jungle'],
    regions: ['Freljord'],
    species: ['Human', 'Iceborn'],
    releaseDate: '2012-01-17',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Senna',
    title: 'the Redeemer',
    gender: 'Female',
    name: 'Senna',
    positions: ['Support'],
    regions: ['Shadow Isles'],
    species: ['Human', 'Undead'],
    releaseDate: '2019-11-10',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Seraphine',
    title: 'the Starry-Eyed Songstress',
    gender: 'Female',
    name: 'Seraphine',
    positions: ['Support'],
    regions: ['Piltover', 'Zaun'],
    species: ['Human', 'Magicborn'],
    releaseDate: '2020-10-29',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Sett',
    title: 'the Boss',
    gender: 'Male',
    name: 'Sett',
    positions: ['Top'],
    regions: ['Ionia'],
    species: ['Human', 'Vastayan'],
    releaseDate: '2020-01-14',
    resource: 'Grit',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Shaco',
    title: 'the Demon Jester',
    gender: 'Male',
    name: 'Shaco',
    positions: ['Jungle'],
    regions: ['Runeterra'],
    species: ['Spirit'],
    releaseDate: '2009-10-10',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Shen',
    title: 'the Eye of Twilight',
    gender: 'Male',
    name: 'Shen',
    positions: ['Top', 'Support'],
    regions: ['Ionia'],
    species: ['Human', 'Spiritualist'],
    releaseDate: '2010-03-24',
    resource: 'Energy',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Shyvana',
    title: 'the Half-Dragon',
    gender: 'Female',
    name: 'Shyvana',
    positions: ['Jungle'],
    regions: ['Demacia'],
    species: ['Dragon', 'Magically Altered'],
    releaseDate: '2011-11-01',
    resource: 'Fury',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Singed',
    title: 'the Mad Chemist',
    gender: 'Male',
    name: 'Singed',
    positions: ['Top'],
    regions: ['Zaun', 'Piltover'],
    species: ['Human', 'Chemically Altered'],
    releaseDate: '2009-04-18',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Sion',
    title: 'The Undead Juggernaut',
    gender: 'Male',
    name: 'Sion',
    positions: ['Top'],
    regions: ['Noxus'],
    species: ['Revenant'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Sivir',
    title: 'the Battle Mistress',
    gender: 'Female',
    name: 'Sivir',
    positions: ['Bottom'],
    regions: ['Shurima'],
    species: ['Human'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Skarner',
    title: 'the Primordial Sovereign',
    gender: 'Male',
    name: 'Skarner',
    positions: ['Top', 'Jungle'],
    regions: ['Ixtal'],
    species: ['Brackern'],
    releaseDate: '2011-08-09',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Smolder',
    title: 'the Fiery Fledgling',
    gender: 'Male',
    name: 'Smolder',
    positions: ['Bottom'],
    regions: ['Camavor', 'Noxus'],
    species: ['Dragon'],
    releaseDate: '2024-01-31',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Sona',
    title: 'Maven of the Strings',
    gender: 'Female',
    name: 'Sona',
    positions: ['Support'],
    regions: ['Demacia', 'Ionia'],
    species: ['Human', 'Magicborn'],
    releaseDate: '2010-09-21',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Soraka',
    title: 'the Starchild',
    gender: 'Female',
    name: 'Soraka',
    positions: ['Support'],
    regions: ['Targon', 'Ionia'],
    species: ['Celestial'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Swain',
    title: 'the Noxian Grand General',
    gender: 'Male',
    name: 'Swain',
    positions: ['Support'],
    regions: ['Noxus'],
    species: ['Human', 'Magically Altered'],
    releaseDate: '2010-10-05',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Sylas',
    title: 'the Unshackled',
    gender: 'Male',
    name: 'Sylas',
    positions: ['Jungle', 'Middle'],
    regions: ['Demacia', 'Freljord'],
    species: ['Human', 'Magicborn'],
    releaseDate: '2019-01-25',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Syndra',
    title: 'the Dark Sovereign',
    gender: 'Female',
    name: 'Syndra',
    positions: ['Middle'],
    regions: ['Ionia'],
    species: ['Human', 'Magicborn'],
    releaseDate: '2012-09-13',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'TahmKench',
    title: 'The River King',
    gender: 'Male',
    name: 'Tahm Kench',
    positions: ['Top', 'Support'],
    regions: ['Bilgewater', 'Runeterra'],
    species: ['Demon', 'Spirit'],
    releaseDate: '2015-07-09',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Taliyah',
    title: 'the Stoneweaver',
    gender: 'Female',
    name: 'Taliyah',
    positions: ['Jungle', 'Middle'],
    regions: ['Shurima'],
    species: ['Human', 'Magicborn'],
    releaseDate: '2016-05-18',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Talon',
    title: "the Blade's Shadow",
    gender: 'Male',
    name: 'Talon',
    positions: ['Jungle', 'Middle'],
    regions: ['Noxus'],
    species: ['Human'],
    releaseDate: '2011-08-24',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Taric',
    title: 'the Shield of Valoran',
    gender: 'Male',
    name: 'Taric',
    positions: ['Support'],
    regions: ['Targon', 'Demacia'],
    species: ['Human', 'Aspect'],
    releaseDate: '2009-08-19',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Teemo',
    title: 'the Swift Scout',
    gender: 'Male',
    name: 'Teemo',
    positions: ['Top'],
    regions: ['Bandle City'],
    species: ['Yordle'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Thresh',
    title: 'the Chain Warden',
    gender: 'Male',
    name: 'Thresh',
    positions: ['Support'],
    regions: ['Shadow Isles'],
    species: ['Undead'],
    releaseDate: '2013-01-23',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Tristana',
    title: 'the Yordle Gunner',
    gender: 'Female',
    name: 'Tristana',
    positions: ['Middle', 'Bottom'],
    regions: ['Bandle City'],
    species: ['Yordle'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Trundle',
    title: 'the Troll King',
    gender: 'Male',
    name: 'Trundle',
    positions: ['Top', 'Jungle'],
    regions: ['Freljord'],
    species: ['Troll', 'Iceborn'],
    releaseDate: '2010-12-01',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Tryndamere',
    title: 'the Barbarian King',
    gender: 'Male',
    name: 'Tryndamere',
    positions: ['Top'],
    regions: ['Freljord'],
    species: ['Human', 'Magically Altered'],
    releaseDate: '2009-05-01',
    resource: 'Fury',
    rangeTypes: ['Melee'],
  },
  {
    id: 'TwistedFate',
    title: 'the Card Master',
    gender: 'Male',
    name: 'Twisted Fate',
    positions: ['Top', 'Middle'],
    regions: ['Bilgewater'],
    species: ['Human', 'Magicborn'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Twitch',
    title: 'the Plague Rat',
    gender: 'Male',
    name: 'Twitch',
    positions: ['Bottom'],
    regions: ['Zaun'],
    species: ['Rat', 'Chemically Altered'],
    releaseDate: '2009-05-01',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Udyr',
    title: 'the Spirit Walker',
    gender: 'Male',
    name: 'Udyr',
    positions: ['Jungle'],
    regions: ['Freljord', 'Ionia'],
    species: ['Human', 'Spiritualist'],
    releaseDate: '2009-12-02',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Urgot',
    title: 'the Dreadnought',
    gender: 'Male',
    name: 'Urgot',
    positions: ['Top'],
    regions: ['Noxus', 'Zaun'],
    species: ['Human', 'Chemically Altered', 'Cyborg'],
    releaseDate: '2010-08-24',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Varus',
    title: 'the Arrow of Retribution',
    gender: 'Male',
    name: 'Varus',
    positions: ['Bottom'],
    regions: ['Ionia', 'Runeterra', 'Shurima'],
    species: ['Darkin', 'Human'],
    releaseDate: '2012-05-08',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Vayne',
    title: 'the Night Hunter',
    gender: 'Female',
    name: 'Vayne',
    positions: ['Top', 'Bottom'],
    regions: ['Demacia'],
    species: ['Human'],
    releaseDate: '2011-05-10',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Veigar',
    title: 'the Tiny Master of Evil',
    gender: 'Male',
    name: 'Veigar',
    positions: ['Middle'],
    regions: ['Runeterra', 'Bandle City', 'Shadow Isles'],
    species: ['Yordle'],
    releaseDate: '2009-07-24',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Velkoz',
    title: 'the Eye of the Void',
    gender: 'Male',
    name: "Vel'Koz",
    positions: ['Middle', 'Support'],
    regions: ['Void'],
    species: ['Void-Being'],
    releaseDate: '2014-02-27',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Vex',
    title: 'the Gloomist',
    gender: 'Female',
    name: 'Vex',
    positions: ['Middle'],
    regions: ['Shadow Isles', 'Bandle City'],
    species: ['Yordle'],
    releaseDate: '2021-09-23',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Vi',
    title: 'the Piltover Enforcer',
    gender: 'Female',
    name: 'Vi',
    positions: ['Jungle'],
    regions: ['Piltover', 'Zaun'],
    species: ['Human'],
    releaseDate: '2012-12-19',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Viego',
    title: 'The Ruined King',
    gender: 'Male',
    name: 'Viego',
    positions: ['Jungle'],
    regions: ['Shadow Isles', 'Camavor'],
    species: ['Undead'],
    releaseDate: '2021-01-21',
    resource: 'Manaless',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Viktor',
    title: 'the Machine Herald',
    gender: 'Male',
    name: 'Viktor',
    positions: ['Middle'],
    regions: ['Piltover', 'Zaun'],
    species: ['Human', 'Cyborg'],
    releaseDate: '2011-12-29',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Vladimir',
    title: 'the Crimson Reaper',
    gender: 'Male',
    name: 'Vladimir',
    positions: ['Top', 'Middle'],
    regions: ['Noxus', 'Shadow Isles', 'Camavor'],
    species: ['Human', 'Magically Altered'],
    releaseDate: '2010-07-27',
    resource: 'Bloodthirst',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Volibear',
    title: 'the Relentless Storm',
    gender: 'Male',
    name: 'Volibear',
    positions: ['Top', 'Jungle'],
    regions: ['Freljord'],
    species: ['Spirit', 'God'],
    releaseDate: '2011-11-29',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Warwick',
    title: 'the Uncaged Wrath of Zaun',
    gender: 'Male',
    name: 'Warwick',
    positions: ['Top', 'Jungle'],
    regions: ['Zaun'],
    species: ['Human', 'Chemically Altered', 'Cyborg'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Xayah',
    title: 'the Rebel',
    gender: 'Female',
    name: 'Xayah',
    positions: ['Bottom'],
    regions: ['Ionia'],
    species: ['Vastayan'],
    releaseDate: '2017-04-19',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Xerath',
    title: 'the Magus Ascendant',
    gender: 'Male',
    name: 'Xerath',
    positions: ['Middle', 'Support'],
    regions: ['Shurima'],
    species: ['God-Warrior'],
    releaseDate: '2011-10-05',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'XinZhao',
    title: 'the Seneschal of Demacia',
    gender: 'Male',
    name: 'Xin Zhao',
    positions: ['Jungle'],
    regions: ['Demacia', 'Ionia', 'Noxus'],
    species: ['Human'],
    releaseDate: '2010-07-13',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Yasuo',
    title: 'the Unforgiven',
    gender: 'Male',
    name: 'Yasuo',
    positions: ['Middle'],
    regions: ['Ionia'],
    species: ['Human', 'Magicborn'],
    releaseDate: '2013-12-13',
    resource: 'Flow',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Yone',
    title: 'the Unforgotten',
    gender: 'Male',
    name: 'Yone',
    positions: ['Top', 'Middle'],
    regions: ['Ionia'],
    species: ['Human', 'Magically Altered'],
    releaseDate: '2020-08-06',
    resource: 'Manaless',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Yorick',
    title: 'Shepherd of Souls',
    gender: 'Male',
    name: 'Yorick',
    positions: ['Top'],
    regions: ['Shadow Isles'],
    species: ['Human', 'Magically Altered'],
    releaseDate: '2011-06-22',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Yuumi',
    title: 'the Magical Cat',
    gender: 'Female',
    name: 'Yuumi',
    positions: ['Support'],
    regions: ['Bandle City'],
    species: ['Cat', 'Magically Altered'],
    releaseDate: '2019-05-14',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Zac',
    title: 'the Secret Weapon',
    gender: 'Male',
    name: 'Zac',
    positions: ['Top', 'Jungle'],
    regions: ['Zaun'],
    species: ['Golem'],
    releaseDate: '2013-03-29',
    resource: 'Health costs',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Zed',
    title: 'the Master of Shadows',
    gender: 'Male',
    name: 'Zed',
    positions: ['Middle'],
    regions: ['Ionia'],
    species: ['Human', 'Magically Altered'],
    releaseDate: '2012-11-13',
    resource: 'Energy',
    rangeTypes: ['Melee'],
  },
  {
    id: 'Zeri',
    title: 'The Spark of Zaun',
    gender: 'Female',
    name: 'Zeri',
    positions: ['Bottom'],
    regions: ['Zaun'],
    species: ['Human', 'Magicborn'],
    releaseDate: '2022-01-20',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Ziggs',
    title: 'the Hexplosives Expert',
    gender: 'Male',
    name: 'Ziggs',
    positions: ['Middle', 'Bottom'],
    regions: ['Zaun'],
    species: ['Yordle'],
    releaseDate: '2012-02-01',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Zilean',
    title: 'the Chronokeeper',
    gender: 'Male',
    name: 'Zilean',
    positions: ['Support'],
    regions: ['Runeterra', 'Icathia', 'Shurima'],
    species: ['Human', 'Magicborn'],
    releaseDate: '2009-04-18',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Zoe',
    title: 'the Aspect of Twilight',
    gender: 'Female',
    name: 'Zoe',
    positions: ['Middle'],
    regions: ['Targon'],
    species: ['Human', 'Aspect'],
    releaseDate: '2017-11-21',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    id: 'Zyra',
    title: 'Rise of the Thorns',
    gender: 'Female',
    name: 'Zyra',
    positions: ['Support'],
    regions: ['Ixtal'],
    species: ['Unknown'],
    releaseDate: '2012-07-24',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
] as Champion[];
