export interface Champion {
  name: string;
  title: string;
  roles: string[];
  portrait: string;
  lanes: string[];
  region: string;
  species: string;
  releaseDate: string;
  resource: string;
  rangeType: string;
}

export const ChampionData = [
  {
    name: 'Aatrox',
    title: 'the Darkin Blade',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Aatrox.png',
    lanes: ['Top'],
    region: 'Runeterra',
    species: 'Darkin',
    releaseDate: '2013-06-13',
    resource: 'Blood Well',
    rangeType: 'Melee',
  },
  {
    name: 'Ahri',
    title: 'the Nine-Tailed Fox',
    roles: ['Assassin', 'Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Ahri.png',
    lanes: ['Middle'],
    region: 'Ionia',
    species: 'Vastayan',
    releaseDate: '2011-12-14',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Akali',
    title: 'the Rogue Assassin',
    roles: ['Assassin'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Akali.png',
    lanes: ['Middle', 'Top'],
    region: 'Ionia',
    species: 'Human',
    releaseDate: '2010-05-11',
    resource: 'Energy',
    rangeType: 'Melee',
  },
  {
    name: 'Akshan',
    title: 'the Rogue Sentinel',
    roles: ['Assassin', 'Marksman'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Akshan.png',
    lanes: ['Middle'],
    region: 'Shurima',
    species: 'Human',
    releaseDate: '2021-07-22',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Alistar',
    title: 'the Minotaur',
    roles: ['Tank', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Alistar.png',
    lanes: ['Support'],
    region: 'Runeterra',
    species: 'Minotaur',
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Amumu',
    title: 'the Sad Mummy',
    roles: ['Tank', 'Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Amumu.png',
    lanes: ['Support'],
    region: 'Shurima',
    species: 'Unknown',
    releaseDate: '2009-06-26',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Anivia',
    title: 'the Cryophoenix',
    roles: ['Mage', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Anivia.png',
    lanes: ['Middle'],
    region: 'Freljord',
    species: 'Spirit God',
    releaseDate: '2009-07-10',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Annie',
    title: 'the Dark Child',
    roles: ['Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Annie.png',
    lanes: ['Middle'],
    region: 'Runeterra',
    species: 'Human',
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Aphelios',
    title: 'the Weapon of the Faithful',
    roles: ['Marksman'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Aphelios.png',
    lanes: ['Bottom'],
    region: 'Targon',
    species: 'Human',
    releaseDate: '2019-12-11',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Ashe',
    title: 'the Frost Archer',
    roles: ['Marksman', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Ashe.png',
    lanes: ['Support', 'Bottom'],
    region: 'Freljord',
    species: 'Human',
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Aurelion Sol',
    title: 'The Star Forger',
    roles: ['Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/AurelionSol.png',
    lanes: ['Middle'],
    region: 'Targon',
    species: 'Celestial',
    releaseDate: '2016-03-24',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Azir',
    title: 'the Emperor of the Sands',
    roles: ['Mage', 'Marksman'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Azir.png',
    lanes: ['Middle'],
    region: 'Shurima',
    species: 'God-Warrior',
    releaseDate: '2014-09-16',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Bard',
    title: 'the Wandering Caretaker',
    roles: ['Mage', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Bard.png',
    lanes: ['Support'],
    region: 'Runeterra',
    species: 'Celestial',
    releaseDate: '2015-03-12',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: "Bel'Veth",
    title: 'the Empress of the Void',
    roles: ['Fighter'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/12.11.1/img/champion/Belveth.png',
    lanes: ['Jungle'],
    region: 'Void',
    species: 'Voidborn',
    releaseDate: '2022-06-09',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Blitzcrank',
    title: 'the Great Steam Golem',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Blitzcrank.png',
    lanes: ['Support'],
    region: 'Zaun',
    species: 'Golem',
    releaseDate: '2009-09-02',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Brand',
    title: 'the Burning Vengeance',
    roles: ['Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Brand.png',
    lanes: ['Support'],
    region: 'Runeterra',
    species: 'Human',
    releaseDate: '2011-04-12',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Braum',
    title: 'the Heart of the Freljord',
    roles: ['Tank', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Braum.png',
    lanes: ['Support'],
    region: 'Freljord',
    species: 'Human',
    releaseDate: '2014-05-12',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Caitlyn',
    title: 'the Sheriff of Piltover',
    roles: ['Marksman'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Caitlyn.png',
    lanes: ['Bottom'],
    region: 'Piltover',
    species: 'Human',
    releaseDate: '2011-01-04',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Camille',
    title: 'the Steel Shadow',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Camille.png',
    lanes: ['Top'],
    region: 'Piltover',
    species: 'Human',
    releaseDate: '2016-12-07',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Cassiopeia',
    title: "the Serpent's Embrace",
    roles: ['Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Cassiopeia.png',
    lanes: ['Middle'],
    region: 'Noxus',
    species: 'Human',
    releaseDate: '2010-12-14',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: "Cho'Gath",
    title: 'the Terror of the Void',
    roles: ['Tank', 'Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Chogath.png',
    lanes: ['Top'],
    region: 'Void',
    species: 'Voidborn',
    releaseDate: '2009-06-26',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Corki',
    title: 'the Daring Bombardier',
    roles: ['Marksman'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Corki.png',
    lanes: ['Middle'],
    region: 'Bandle City',
    species: 'Yordle',
    releaseDate: '2009-09-19',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Darius',
    title: 'the Hand of Noxus',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Darius.png',
    lanes: ['Top'],
    region: 'Noxus',
    species: 'Human',
    releaseDate: '2012-05-23',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Diana',
    title: 'Scorn of the Moon',
    roles: ['Fighter', 'Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Diana.png',
    lanes: ['Jungle'],
    region: 'Targon',
    species: 'Aspect Host',
    releaseDate: '2012-08-07',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Dr. Mundo',
    title: 'the Madman of Zaun',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/DrMundo.png',
    lanes: ['Top'],
    region: 'Zaun',
    species: 'Human',
    releaseDate: '2009-09-02',
    resource: 'Health',
    rangeType: 'Melee',
  },
  {
    name: 'Draven',
    title: 'the Glorious Executioner',
    roles: ['Marksman'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Draven.png',
    lanes: ['Bottom'],
    region: 'Noxus',
    species: 'Human',
    releaseDate: '2012-06-06',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Ekko',
    title: 'the Boy Who Shattered Time',
    roles: ['Fighter', 'Assassin'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Ekko.png',
    lanes: ['Jungle', 'Middle'],
    region: 'Zaun',
    species: 'Human',
    releaseDate: '2015-05-29',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Elise',
    title: 'the Spider Queen',
    roles: ['Fighter', 'Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Elise.png',
    lanes: ['Jungle'],
    region: 'Shadow Isles',
    species: 'Human',
    releaseDate: '2012-10-26',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Evelynn',
    title: "Agony's Embrace",
    roles: ['Assassin', 'Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Evelynn.png',
    lanes: ['Jungle'],
    region: 'Runeterra',
    species: 'Demon',
    releaseDate: '2009-05-01',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Ezreal',
    title: 'the Prodigal Explorer',
    roles: ['Mage', 'Marksman'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Ezreal.png',
    lanes: ['Bottom'],
    region: 'Piltover',
    species: 'Human',
    releaseDate: '2010-03-16',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Fiddlesticks',
    title: 'the Ancient Fear',
    roles: ['Mage', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Fiddlesticks.png',
    lanes: ['Jungle'],
    region: 'Runeterra',
    species: 'Demon',
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Fiora',
    title: 'the Grand Duelist',
    roles: ['Fighter', 'Assassin'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Fiora.png',
    lanes: ['Top'],
    region: 'Demacia',
    species: 'Human',
    releaseDate: '2012-02-29',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Fizz',
    title: 'the Tidal Trickster',
    roles: ['Fighter', 'Assassin'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Fizz.png',
    lanes: ['Middle'],
    region: 'Bilgewater',
    species: 'Yordle',
    releaseDate: '2011-11-15',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Galio',
    title: 'the Colossus',
    roles: ['Tank', 'Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Galio.png',
    lanes: ['Middle'],
    region: 'Demacia',
    species: 'Golem',
    releaseDate: '2010-08-10',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Gangplank',
    title: 'the Saltwater Scourge',
    roles: ['Fighter'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Gangplank.png',
    lanes: ['Top'],
    region: 'Bilgewater',
    species: 'Human',
    releaseDate: '2009-08-19',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Garen',
    title: 'The Might of Demacia',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Garen.png',
    lanes: ['Top'],
    region: 'Demacia',
    species: 'Human',
    releaseDate: '2010-04-27',
    resource: 'None',
    rangeType: 'Melee',
  },
  {
    name: 'Gnar',
    title: 'the Missing Link',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Gnar.png',
    lanes: ['Top'],
    region: 'Freljord',
    species: 'Yordle',
    releaseDate: '2014-08-14',
    resource: 'Rage',
    rangeType: 'Ranged',
  },
  {
    name: 'Gragas',
    title: 'the Rabble Rouser',
    roles: ['Fighter', 'Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Gragas.png',
    lanes: ['Top'],
    region: 'Freljord',
    species: 'Human',
    releaseDate: '2010-02-02',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Graves',
    title: 'the Outlaw',
    roles: ['Marksman'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Graves.png',
    lanes: ['Jungle'],
    region: 'Bilgewater',
    species: 'Human',
    releaseDate: '2011-10-19',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Gwen',
    title: 'The Hallowed Seamstress',
    roles: ['Fighter', 'Assassin'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Gwen.png',
    lanes: ['Top'],
    region: 'Shadow Isles',
    species: 'Human',
    releaseDate: '2021-04-15',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Hecarim',
    title: 'the Shadow of War',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Hecarim.png',
    lanes: ['Jungle'],
    region: 'Shadow Isles',
    species: 'Wraith',
    releaseDate: '2012-04-18',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Heimerdinger',
    title: 'the Revered Inventor',
    roles: ['Mage', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Heimerdinger.png',
    lanes: ['Support'],
    region: 'Piltover',
    species: 'Yordle',
    releaseDate: '2009-10-10',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Illaoi',
    title: 'the Kraken Priestess',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Illaoi.png',
    lanes: ['Top'],
    region: 'Bilgewater',
    species: 'Human',
    releaseDate: '2015-11-24',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Irelia',
    title: 'the Blade Dancer',
    roles: ['Fighter', 'Assassin'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Irelia.png',
    lanes: ['Middle', 'Top'],
    region: 'Ionia',
    species: 'Human',
    releaseDate: '2010-11-16',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Ivern',
    title: 'the Green Father',
    roles: ['Mage', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Ivern.png',
    lanes: ['Jungle'],
    region: 'Ionia',
    species: 'Human',
    releaseDate: '2016-10-05',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Janna',
    title: "the Storm's Fury",
    roles: ['Mage', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Janna.png',
    lanes: ['Support'],
    region: 'Zaun',
    species: 'Spirit God',
    releaseDate: '2009-09-02',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Jarvan IV',
    title: 'the Exemplar of Demacia',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/JarvanIV.png',
    lanes: ['Jungle'],
    region: 'Demacia',
    species: 'Human',
    releaseDate: '2011-03-01',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Jax',
    title: 'Grandmaster at Arms',
    roles: ['Fighter', 'Assassin'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Jax.png',
    lanes: ['Top'],
    region: 'Runeterra',
    species: 'Unknown',
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Jayce',
    title: 'the Defender of Tomorrow',
    roles: ['Fighter', 'Marksman'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Jayce.png',
    lanes: ['Top'],
    region: 'Piltover',
    species: 'Human',
    releaseDate: '2012-07-07',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Jhin',
    title: 'the Virtuoso',
    roles: ['Mage', 'Marksman'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Jhin.png',
    lanes: ['Bottom'],
    region: 'Ionia',
    species: 'Human',
    releaseDate: '2016-02-01',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Jinx',
    title: 'the Loose Cannon',
    roles: ['Marksman'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Jinx.png',
    lanes: ['Bottom'],
    region: 'Zaun',
    species: 'Human',
    releaseDate: '2013-10-10',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: "K'Sante",
    title: 'the Pride of Nazumah',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/12.21.1/img/champion/KSante.png',
    lanes: ['Top'],
    region: 'Shurima',
    species: 'Human',
    releaseDate: '2022-11-02',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: "Kai'Sa",
    title: 'Daughter of the Void',
    roles: ['Marksman'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Kaisa.png',
    lanes: ['Bottom'],
    region: 'Void',
    species: 'Human',
    releaseDate: '2018-03-07',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Kalista',
    title: 'the Spear of Vengeance',
    roles: ['Marksman'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Kalista.png',
    lanes: ['Bottom'],
    region: 'Shadow Isles',
    species: 'Wraith',
    releaseDate: '2014-11-20',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Karma',
    title: 'the Enlightened One',
    roles: ['Mage', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Karma.png',
    lanes: ['Support'],
    region: 'Ionia',
    species: 'Human',
    releaseDate: '2011-02-01',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Karthus',
    title: 'the Deathsinger',
    roles: ['Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Karthus.png',
    lanes: ['Jungle'],
    region: 'Shadow Isles',
    species: 'Wraith',
    releaseDate: '2009-06-12',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Kassadin',
    title: 'the Void Walker',
    roles: ['Assassin', 'Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Kassadin.png',
    lanes: ['Middle'],
    region: 'Void',
    species: 'Human',
    releaseDate: '2009-08-07',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Katarina',
    title: 'the Sinister Blade',
    roles: ['Assassin', 'Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Katarina.png',
    lanes: ['Middle'],
    region: 'Noxus',
    species: 'Human',
    releaseDate: '2009-09-19',
    resource: 'None',
    rangeType: 'Melee',
  },
  {
    name: 'Kayle',
    title: 'the Righteous',
    roles: ['Fighter', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Kayle.png',
    lanes: ['Top'],
    region: 'Targon',
    species: 'Human',
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Kayn',
    title: 'the Shadow Reaper',
    roles: ['Fighter', 'Assassin'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Kayn.png',
    lanes: ['Jungle'],
    region: 'Ionia',
    species: 'Darkin',
    releaseDate: '2017-07-12',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Kennen',
    title: 'the Heart of the Tempest',
    roles: ['Mage', 'Marksman'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Kennen.png',
    lanes: ['Top'],
    region: 'Ionia',
    species: 'Yordle',
    releaseDate: '2010-04-08',
    resource: 'Energy',
    rangeType: 'Ranged',
  },
  {
    name: "Kha'Zix",
    title: 'the Voidreaver',
    roles: ['Assassin'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Khazix.png',
    lanes: ['Jungle'],
    region: 'Void',
    species: 'Voidborn',
    releaseDate: '2012-09-27',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Kindred',
    title: 'The Eternal Hunters',
    roles: ['Marksman'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Kindred.png',
    lanes: ['Jungle'],
    region: 'Runeterra',
    species: 'Spirit God',
    releaseDate: '2015-10-14',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Kled',
    title: 'the Cantankerous Cavalier',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Kled.png',
    lanes: ['Top'],
    region: 'Noxus',
    species: 'Yordle',
    releaseDate: '2016-08-10',
    resource: 'Courage',
    rangeType: 'Melee',
  },
  {
    name: "Kog'Maw",
    title: 'the Mouth of the Abyss',
    roles: ['Mage', 'Marksman'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/KogMaw.png',
    lanes: ['Bottom'],
    region: 'Void',
    species: 'Voidborn',
    releaseDate: '2010-06-24',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'LeBlanc',
    title: 'the Deceiver',
    roles: ['Assassin', 'Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Leblanc.png',
    lanes: ['Middle'],
    region: 'Noxus',
    species: 'Human',
    releaseDate: '2010-11-02',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Lee Sin',
    title: 'the Blind Monk',
    roles: ['Fighter', 'Assassin'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/LeeSin.png',
    lanes: ['Jungle'],
    region: 'Ionia',
    species: 'Human',
    releaseDate: '2011-04-01',
    resource: 'Energy',
    rangeType: 'Melee',
  },
  {
    name: 'Leona',
    title: 'the Radiant Dawn',
    roles: ['Tank', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Leona.png',
    lanes: ['Support'],
    region: 'Targon',
    species: 'Aspect Host',
    releaseDate: '2011-07-13',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Lillia',
    title: 'the Bashful Bloom',
    roles: ['Fighter', 'Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Lillia.png',
    lanes: ['Jungle'],
    region: 'Ionia',
    species: 'Spirit',
    releaseDate: '2020-07-22',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Lissandra',
    title: 'the Ice Witch',
    roles: ['Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Lissandra.png',
    lanes: ['Middle'],
    region: 'Freljord',
    species: 'Human',
    releaseDate: '2013-04-30',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Lucian',
    title: 'the Purifier',
    roles: ['Marksman'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Lucian.png',
    lanes: ['Bottom'],
    region: 'Blessed Isles',
    species: 'Human',
    releaseDate: '2013-08-22',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Lulu',
    title: 'the Fae Sorceress',
    roles: ['Mage', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Lulu.png',
    lanes: ['Support'],
    region: 'Bandle City',
    species: 'Yordle',
    releaseDate: '2012-03-20',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Lux',
    title: 'the Lady of Luminosity',
    roles: ['Mage', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Lux.png',
    lanes: ['Support', 'Middle'],
    region: 'Demacia',
    species: 'Human',
    releaseDate: '2010-10-19',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Malphite',
    title: 'Shard of the Monolith',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Malphite.png',
    lanes: ['Top'],
    region: 'Ixtal',
    species: 'Golem',
    releaseDate: '2009-09-02',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Malzahar',
    title: 'the Prophet of the Void',
    roles: ['Assassin', 'Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Malzahar.png',
    lanes: ['Middle'],
    region: 'Void',
    species: 'Human',
    releaseDate: '2010-06-01',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Maokai',
    title: 'the Twisted Treant',
    roles: ['Tank', 'Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Maokai.png',
    lanes: ['Support'],
    region: 'Shadow Isles',
    species: 'Spirit',
    releaseDate: '2011-02-16',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Master Yi',
    title: 'the Wuju Bladesman',
    roles: ['Fighter', 'Assassin'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/MasterYi.png',
    lanes: ['Jungle'],
    region: 'Ionia',
    species: 'Human',
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Miss Fortune',
    title: 'the Bounty Hunter',
    roles: ['Marksman'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/MissFortune.png',
    lanes: ['Bottom'],
    region: 'Bilgewater',
    species: 'Human',
    releaseDate: '2010-09-08',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Mordekaiser',
    title: 'the Iron Revenant',
    roles: ['Fighter'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Mordekaiser.png',
    lanes: ['Jungle', 'Top'],
    region: 'Noxus',
    species: 'Revenant',
    releaseDate: '2010-02-24',
    resource: 'Shield',
    rangeType: 'Melee',
  },
  {
    name: 'Morgana',
    title: 'the Fallen',
    roles: ['Mage', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Morgana.png',
    lanes: ['Support'],
    region: 'Targon',
    species: 'Human',
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Nami',
    title: 'the Tidecaller',
    roles: ['Mage', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Nami.png',
    lanes: ['Support'],
    region: 'Runeterra',
    species: 'Vastayan',
    releaseDate: '2012-12-07',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Nasus',
    title: 'the Curator of the Sands',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Nasus.png',
    lanes: ['Top'],
    region: 'Shurima',
    species: 'God-Warrior',
    releaseDate: '2009-10-01',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Nautilus',
    title: 'the Titan of the Depths',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Nautilus.png',
    lanes: ['Support'],
    region: 'Bilgewater',
    species: 'Revenant',
    releaseDate: '2012-02-14',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Neeko',
    title: 'the Curious Chameleon',
    roles: ['Mage', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Neeko.png',
    lanes: ['Middle'],
    region: 'Ixtal',
    species: 'Vastayan',
    releaseDate: '2018-12-05',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Nidalee',
    title: 'the Bestial Huntress',
    roles: ['Assassin', 'Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Nidalee.png',
    lanes: ['Jungle'],
    region: 'Ixtal',
    species: 'Human',
    releaseDate: '2009-12-17',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Nilah',
    title: 'the Joy Unbound',
    roles: ['Fighter', 'Assassin'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/12.13.1/img/champion/Nilah.png',
    lanes: ['Bottom'],
    region: 'Bilgewater',
    species: 'Human',
    releaseDate: '2022-07-13',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Nocturne',
    title: 'the Eternal Nightmare',
    roles: ['Fighter', 'Assassin'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Nocturne.png',
    lanes: ['Jungle'],
    region: 'Runeterra',
    species: 'Demon',
    releaseDate: '2011-03-15',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Nunu & Willump',
    title: 'the Boy and His Yeti',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Nunu.png',
    lanes: ['Jungle'],
    region: 'Freljord',
    species: 'Human',
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Olaf',
    title: 'the Berserker',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Olaf.png',
    lanes: ['Top'],
    region: 'Freljord',
    species: 'Human',
    releaseDate: '2010-06-09',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Orianna',
    title: 'the Lady of Clockwork',
    roles: ['Mage', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Orianna.png',
    lanes: ['Middle'],
    region: 'Piltover',
    species: 'Golem',
    releaseDate: '2011-06-01',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Ornn',
    title: 'The Fire below the Mountain',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Ornn.png',
    lanes: ['Top'],
    region: 'Freljord',
    species: 'Spirit God',
    releaseDate: '2017-08-23',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Pantheon',
    title: 'the Unbreakable Spear',
    roles: ['Fighter', 'Assassin'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Pantheon.png',
    lanes: ['Support'],
    region: 'Targon',
    species: 'Aspect Host',
    releaseDate: '2010-02-02',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Poppy',
    title: 'Keeper of the Hammer',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Poppy.png',
    lanes: ['Jungle'],
    region: 'Demacia',
    species: 'Yordle',
    releaseDate: '2010-01-13',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Pyke',
    title: 'the Bloodharbor Ripper',
    roles: ['Assassin', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Pyke.png',
    lanes: ['Support'],
    region: 'Bilgewater',
    species: 'Revenant',
    releaseDate: '2018-05-31',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Qiyana',
    title: 'Empress of the Elements',
    roles: ['Fighter', 'Assassin'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Qiyana.png',
    lanes: ['Middle'],
    region: 'Ixtal',
    species: 'Human',
    releaseDate: '2019-06-28',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Quinn',
    title: "Demacia's Wings",
    roles: ['Assassin', 'Marksman'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Quinn.png',
    lanes: ['Top'],
    region: 'Demacia',
    species: 'Human',
    releaseDate: '2013-03-01',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Rakan',
    title: 'The Charmer',
    roles: ['Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Rakan.png',
    lanes: ['Support'],
    region: 'Ionia',
    species: 'Vastayan',
    releaseDate: '2017-04-19',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Rammus',
    title: 'the Armordillo',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Rammus.png',
    lanes: ['Jungle'],
    region: 'Shurima',
    species: 'Unknown',
    releaseDate: '2009-07-10',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: "Rek'Sai",
    title: 'the Void Burrower',
    roles: ['Fighter'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/RekSai.png',
    lanes: ['Jungle'],
    region: 'Void',
    species: 'Voidborn',
    releaseDate: '2014-12-11',
    resource: 'Rage',
    rangeType: 'Melee',
  },
  {
    name: 'Rell',
    title: 'the Iron Maiden',
    roles: ['Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Rell.png',
    lanes: ['Support'],
    region: 'Noxus',
    species: 'Human',
    releaseDate: '2020-12-10',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Renata Glasc',
    title: 'the Chem-Baroness',
    roles: ['Mage', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/12.7.1/img/champion/Renata.png',
    lanes: ['Support'],
    region: 'Zaun',
    species: 'Human',
    releaseDate: '2022-02-17',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Renekton',
    title: 'the Butcher of the Sands',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Renekton.png',
    lanes: ['Top'],
    region: 'Shurima',
    species: 'God-Warrior',
    releaseDate: '2011-01-18',
    resource: 'Fury',
    rangeType: 'Melee',
  },
  {
    name: 'Rengar',
    title: 'the Pridestalker',
    roles: ['Fighter', 'Assassin'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Rengar.png',
    lanes: ['Jungle'],
    region: 'Ixtal',
    species: 'Vastayan',
    releaseDate: '2012-08-21',
    resource: 'Ferocity',
    rangeType: 'Melee',
  },
  {
    name: 'Riven',
    title: 'the Exile',
    roles: ['Fighter', 'Assassin'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Riven.png',
    lanes: ['Top'],
    region: 'Noxus',
    species: 'Human',
    releaseDate: '2011-09-14',
    resource: 'None',
    rangeType: 'Melee',
  },
  {
    name: 'Rumble',
    title: 'the Mechanized Menace',
    roles: ['Fighter', 'Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Rumble.png',
    lanes: ['Middle', 'Top'],
    region: 'Bandle City',
    species: 'Yordle',
    releaseDate: '2011-04-26',
    resource: 'Heat',
    rangeType: 'Melee',
  },
  {
    name: 'Ryze',
    title: 'the Rune Mage',
    roles: ['Fighter', 'Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Ryze.png',
    lanes: ['Middle'],
    region: 'Runeterra',
    species: 'Human',
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Samira',
    title: 'the Desert Rose',
    roles: ['Marksman'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Samira.png',
    lanes: ['Bottom'],
    region: 'Noxus',
    species: 'Human',
    releaseDate: '2020-09-21',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Sejuani',
    title: 'Fury of the North',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Sejuani.png',
    lanes: ['Jungle'],
    region: 'Freljord',
    species: 'Human',
    releaseDate: '2012-01-17',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Senna',
    title: 'the Redeemer',
    roles: ['Marksman', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Senna.png',
    lanes: ['Support'],
    region: 'Blessed Isles',
    species: 'Human',
    releaseDate: '2019-11-10',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Seraphine',
    title: 'the Starry-Eyed Songstress',
    roles: ['Mage', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Seraphine.png',
    lanes: ['Support'],
    region: 'Piltover',
    species: 'Human',
    releaseDate: '2020-10-29',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Sett',
    title: 'the Boss',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Sett.png',
    lanes: ['Top'],
    region: 'Ionia',
    species: 'Vastayan',
    releaseDate: '2020-01-14',
    resource: 'Grit',
    rangeType: 'Melee',
  },
  {
    name: 'Shaco',
    title: 'the Demon Jester',
    roles: ['Assassin'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Shaco.png',
    lanes: ['Jungle'],
    region: 'Runeterra',
    species: 'Spirit',
    releaseDate: '2009-10-10',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Shen',
    title: 'the Eye of Twilight',
    roles: ['Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Shen.png',
    lanes: ['Top'],
    region: 'Ionia',
    species: 'Human',
    releaseDate: '2010-03-24',
    resource: 'Energy',
    rangeType: 'Melee',
  },
  {
    name: 'Shyvana',
    title: 'the Half-Dragon',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Shyvana.png',
    lanes: ['Jungle'],
    region: 'Demacia',
    species: 'Terrestrial Dragon',
    releaseDate: '2011-11-01',
    resource: 'Fury',
    rangeType: 'Melee',
  },
  {
    name: 'Singed',
    title: 'the Mad Chemist',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Singed.png',
    lanes: ['Top'],
    region: 'Zaun',
    species: 'Human',
    releaseDate: '2009-04-18',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Sion',
    title: 'The Undead Juggernaut',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Sion.png',
    lanes: ['Top'],
    region: 'Noxus',
    species: 'Revenant',
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Sivir',
    title: 'the Battle Mistress',
    roles: ['Marksman'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Sivir.png',
    lanes: ['Bottom'],
    region: 'Shurima',
    species: 'Human',
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Skarner',
    title: 'the Crystal Vanguard',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Skarner.png',
    lanes: ['Jungle'],
    region: 'Shurima',
    species: 'Brackern',
    releaseDate: '2011-08-09',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Sona',
    title: 'Maven of the Strings',
    roles: ['Mage', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Sona.png',
    lanes: ['Support'],
    region: 'Demacia',
    species: 'Human',
    releaseDate: '2010-09-21',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Soraka',
    title: 'the Starchild',
    roles: ['Mage', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Soraka.png',
    lanes: ['Support'],
    region: 'Targon',
    species: 'Celestial',
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Swain',
    title: 'the Noxian Grand General',
    roles: ['Fighter', 'Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Swain.png',
    lanes: ['Support', 'Middle'],
    region: 'Noxus',
    species: 'Human',
    releaseDate: '2010-10-05',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Sylas',
    title: 'the Unshackled',
    roles: ['Assassin', 'Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Sylas.png',
    lanes: ['Jungle', 'Middle'],
    region: 'Demacia',
    species: 'Human',
    releaseDate: '2019-01-25',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Syndra',
    title: 'the Dark Sovereign',
    roles: ['Mage', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Syndra.png',
    lanes: ['Middle'],
    region: 'Ionia',
    species: 'Human',
    releaseDate: '2012-09-13',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Tahm Kench',
    title: 'The River King',
    roles: ['Tank', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/TahmKench.png',
    lanes: ['Top'],
    region: 'Runeterra',
    species: 'Demon',
    releaseDate: '2015-07-09',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Taliyah',
    title: 'the Stoneweaver',
    roles: ['Mage', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Taliyah.png',
    lanes: ['Jungle', 'Middle'],
    region: 'Shurima',
    species: 'Human',
    releaseDate: '2016-05-18',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Talon',
    title: "the Blade's Shadow",
    roles: ['Assassin'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Talon.png',
    lanes: ['Middle'],
    region: 'Noxus',
    species: 'Human',
    releaseDate: '2011-08-24',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Taric',
    title: 'the Shield of Valoran',
    roles: ['Fighter', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Taric.png',
    lanes: ['Support'],
    region: 'Targon',
    species: 'Aspect Host',
    releaseDate: '2009-08-19',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Teemo',
    title: 'the Swift Scout',
    roles: ['Assassin', 'Marksman'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Teemo.png',
    lanes: ['Top'],
    region: 'Bandle City',
    species: 'Yordle',
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Thresh',
    title: 'the Chain Warden',
    roles: ['Fighter', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Thresh.png',
    lanes: ['Support'],
    region: 'Shadow Isles',
    species: 'Wraith',
    releaseDate: '2013-01-23',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Tristana',
    title: 'the Yordle Gunner',
    roles: ['Assassin', 'Marksman'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Tristana.png',
    lanes: ['Bottom'],
    region: 'Bandle City',
    species: 'Yordle',
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Trundle',
    title: 'the Troll King',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Trundle.png',
    lanes: ['Jungle'],
    region: 'Freljord',
    species: 'Troll',
    releaseDate: '2010-12-01',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Tryndamere',
    title: 'the Barbarian King',
    roles: ['Fighter', 'Assassin'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Tryndamere.png',
    lanes: ['Top'],
    region: 'Freljord',
    species: 'Human',
    releaseDate: '2009-05-01',
    resource: 'Fury',
    rangeType: 'Melee',
  },
  {
    name: 'Twisted Fate',
    title: 'the Card Master',
    roles: ['Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/TwistedFate.png',
    lanes: ['Middle'],
    region: 'Bilgewater',
    species: 'Human',
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Twitch',
    title: 'the Plague Rat',
    roles: ['Assassin', 'Marksman'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Twitch.png',
    lanes: ['Bottom'],
    region: 'Zaun',
    species: 'Plague Rat',
    releaseDate: '2009-05-01',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Udyr',
    title: 'the Spirit Walker',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/12.17.1/img/champion/Udyr.png',
    lanes: ['Jungle'],
    region: 'Freljord',
    species: 'Human',
    releaseDate: '2009-12-02',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Urgot',
    title: 'the Dreadnought',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Urgot.png',
    lanes: ['Top'],
    region: 'Zaun',
    species: 'Human',
    releaseDate: '2010-08-24',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Varus',
    title: 'the Arrow of Retribution',
    roles: ['Mage', 'Marksman'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Varus.png',
    lanes: ['Middle', 'Bottom'],
    region: 'Ionia',
    species: 'Darkin',
    releaseDate: '2012-05-08',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Vayne',
    title: 'the Night Hunter',
    roles: ['Assassin', 'Marksman'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Vayne.png',
    lanes: ['Bottom'],
    region: 'Demacia',
    species: 'Human',
    releaseDate: '2011-05-10',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Veigar',
    title: 'the Tiny Master of Evil',
    roles: ['Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Veigar.png',
    lanes: ['Middle'],
    region: 'Bandle City',
    species: 'Yordle',
    releaseDate: '2009-07-24',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: "Vel'Koz",
    title: 'the Eye of the Void',
    roles: ['Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Velkoz.png',
    lanes: ['Support'],
    region: 'Void',
    species: 'Voidborn',
    releaseDate: '2014-02-27',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Vex',
    title: 'the Gloomist',
    roles: ['Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Vex.png',
    lanes: ['Middle'],
    region: 'Shadow Isles',
    species: 'Yordle',
    releaseDate: '2021-09-23',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Vi',
    title: 'the Piltover Enforcer',
    roles: ['Fighter', 'Assassin'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Vi.png',
    lanes: ['Jungle'],
    region: 'Piltover',
    species: 'Human',
    releaseDate: '2012-12-19',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Viego',
    title: 'The Ruined King',
    roles: ['Fighter', 'Assassin'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Viego.png',
    lanes: ['Jungle'],
    region: 'Shadow Isles',
    species: 'Wraith',
    releaseDate: '2021-01-22',
    resource: 'None',
    rangeType: 'Melee',
  },
  {
    name: 'Viktor',
    title: 'the Machine Herald',
    roles: ['Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Viktor.png',
    lanes: ['Middle'],
    region: 'Zaun',
    species: 'Human',
    releaseDate: '2011-12-29',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Vladimir',
    title: 'the Crimson Reaper',
    roles: ['Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Vladimir.png',
    lanes: ['Middle'],
    region: 'Noxus',
    species: 'Human',
    releaseDate: '2010-07-27',
    resource: 'Crimson Rush',
    rangeType: 'Ranged',
  },
  {
    name: 'Volibear',
    title: 'the Relentless Storm',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Volibear.png',
    lanes: ['Jungle', 'Top'],
    region: 'Freljord',
    species: 'Spirit God',
    releaseDate: '2011-11-29',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Warwick',
    title: 'the Uncaged Wrath of Zaun',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Warwick.png',
    lanes: ['Jungle'],
    region: 'Zaun',
    species: 'Human',
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Wukong',
    title: 'the Monkey King',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/MonkeyKing.png',
    lanes: ['Jungle'],
    region: 'Ionia',
    species: 'Vastayan',
    releaseDate: '2011-07-26',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Xayah',
    title: 'the Rebel',
    roles: ['Marksman'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Xayah.png',
    lanes: ['Bottom'],
    region: 'Ionia',
    species: 'Vastayan',
    releaseDate: '2017-04-19',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Xerath',
    title: 'the Magus Ascendant',
    roles: ['Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Xerath.png',
    lanes: ['Support'],
    region: 'Shurima',
    species: 'Baccai',
    releaseDate: '2011-10-05',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Xin Zhao',
    title: 'the Seneschal of Demacia',
    roles: ['Fighter', 'Assassin'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/XinZhao.png',
    lanes: ['Jungle'],
    region: 'Demacia',
    species: 'Human',
    releaseDate: '2010-07-13',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Yasuo',
    title: 'the Unforgiven',
    roles: ['Fighter', 'Assassin'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Yasuo.png',
    lanes: ['Middle', 'Top'],
    region: 'Ionia',
    species: 'Human',
    releaseDate: '2013-12-13',
    resource: 'Flow',
    rangeType: 'Melee',
  },
  {
    name: 'Yone',
    title: 'the Unforgotten',
    roles: ['Fighter', 'Assassin'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Yone.png',
    lanes: ['Middle', 'Top'],
    region: 'Ionia',
    species: 'Human',
    releaseDate: '2020-08-06',
    resource: 'Flow',
    rangeType: 'Melee',
  },
  {
    name: 'Yorick',
    title: 'Shepherd of Souls',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Yorick.png',
    lanes: ['Top'],
    region: 'Shadow Isles',
    species: 'Human',
    releaseDate: '2011-06-22',
    resource: 'Mana',
    rangeType: 'Melee',
  },
  {
    name: 'Yuumi',
    title: 'the Magical Cat',
    roles: ['Mage', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Yuumi.png',
    lanes: ['Support'],
    region: 'Bandle City',
    species: 'Cat',
    releaseDate: '2019-05-14',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Zac',
    title: 'the Secret Weapon',
    roles: ['Fighter', 'Tank'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Zac.png',
    lanes: ['Jungle'],
    region: 'Zaun',
    species: 'Golem',
    releaseDate: '2013-03-29',
    resource: 'Health',
    rangeType: 'Melee',
  },
  {
    name: 'Zed',
    title: 'the Master of Shadows',
    roles: ['Assassin'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Zed.png',
    lanes: ['Jungle', 'Middle'],
    region: 'Ionia',
    species: 'Human',
    releaseDate: '2012-11-13',
    resource: 'Energy',
    rangeType: 'Melee',
  },
  {
    name: 'Zeri',
    title: 'The Spark of Zaun',
    roles: ['Marksman'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/12.7.1/img/champion/Zeri.png',
    lanes: ['Bottom'],
    region: 'Zaun',
    species: 'Human',
    releaseDate: '2022-01-20',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Ziggs',
    title: 'the Hexplosives Expert',
    roles: ['Mage'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Ziggs.png',
    lanes: ['Middle'],
    region: 'Zaun',
    species: 'Yordle',
    releaseDate: '2012-02-01',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Zilean',
    title: 'the Chronokeeper',
    roles: ['Mage', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Zilean.png',
    lanes: ['Support'],
    region: 'Runeterra',
    species: 'Human',
    releaseDate: '2009-04-18',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Zoe',
    title: 'the Aspect of Twilight',
    roles: ['Mage', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Zoe.png',
    lanes: ['Middle'],
    region: 'Targon',
    species: 'Aspect Host',
    releaseDate: '2017-11-21',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
  {
    name: 'Zyra',
    title: 'Rise of the Thorns',
    roles: ['Mage', 'Support'],
    portrait: 'https://ddragon.leagueoflegends.com/cdn/11.23.1/img/champion/Zyra.png',
    lanes: ['Support'],
    region: 'Ixtal',
    species: 'Unknown',
    releaseDate: '2012-07-24',
    resource: 'Mana',
    rangeType: 'Ranged',
  },
] as Champion[];
