export interface Champion {
  id: string;
  gender: string;
  name: string;
  lanes: string[];
  regions: string[];
  species: string[];
  releaseDate: string;
  resource: string;
  rangeTypes: string[];
}

export const ChampionData = [
  {
    name: 'Aatrox',
    lanes: ['Top'],
    regions: ['Runeterra', 'Shurima'],
    species: ['Darkin'],
    releaseDate: '2013-06-13',
    resource: 'Manaless',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Ahri',
    lanes: ['Middle'],
    regions: ['Ionia'],
    species: ['Vastayan'],
    releaseDate: '2011-12-14',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Akali',
    lanes: ['Top', 'Middle'],
    regions: ['Ionia'],
    species: ['Human'],
    releaseDate: '2010-05-11',
    resource: 'Energy',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Akshan',
    lanes: ['Middle'],
    regions: ['Shurima'],
    species: ['Human'],
    releaseDate: '2021-07-22',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Alistar',
    lanes: ['Support'],
    regions: ['Runeterra'],
    species: ['Minotaur'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Amumu',
    lanes: ['Jungle'],
    regions: ['Shurima'],
    species: ['Undead', 'Yordle'],
    releaseDate: '2009-06-26',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Anivia',
    lanes: ['Middle'],
    regions: ['Freljord'],
    species: ['Spirit', 'God'],
    releaseDate: '2009-07-10',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Annie',
    lanes: ['Middle'],
    regions: ['Noxus', 'Runeterra'],
    species: ['Human', 'Magicborn'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Aphelios',
    lanes: ['Bottom'],
    regions: ['Targon'],
    species: ['Human', 'Spiritualist'],
    releaseDate: '2019-12-11',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Ashe',
    lanes: ['Bottom'],
    regions: ['Freljord'],
    species: ['Human', 'Iceborn'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Aurora',
    lanes: ['Middle'],
    regions: ['Freljord'],
    species: ['Vastayan'],
    releaseDate: '2024-07-14',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Aurelion Sol',
    lanes: ['Middle'],
    regions: ['Runeterra', 'Targon'],
    species: ['Celestial', 'Dragon'],
    releaseDate: '2016-03-24',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Azir',
    lanes: ['Middle'],
    regions: ['Shurima'],
    species: ['God-Warrior'],
    releaseDate: '2014-09-16',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Bard',
    lanes: ['Support'],
    regions: ['Runeterra'],
    species: ['Celestial'],
    releaseDate: '2015-03-12',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: "Bel'Veth",
    lanes: ['Jungle'],
    regions: ['Void'],
    species: ['Void-Being'],
    releaseDate: '2022-06-09',
    resource: 'Manaless',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Blitzcrank',
    lanes: ['Support'],
    regions: ['Zaun'],
    species: ['Golem'],
    releaseDate: '2009-09-02',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Brand',
    lanes: ['Jungle', 'Middle', 'Support'],
    regions: ['Freljord', 'Runeterra'],
    species: ['Human', 'Magically Altered'],
    releaseDate: '2011-04-12',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Braum',
    lanes: ['Support'],
    regions: ['Freljord'],
    species: ['Human', 'Iceborn'],
    releaseDate: '2014-05-12',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Briar',
    lanes: ['Jungle'],
    regions: ['Noxus'],
    species: ['Golem'],
    releaseDate: '2023-09-14',
    resource: 'Health costs',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Caitlyn',
    lanes: ['Bottom'],
    regions: ['Piltover'],
    species: ['Human'],
    releaseDate: '2011-01-04',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Camille',
    lanes: ['Top'],
    regions: ['Piltover'],
    species: ['Human', 'Cyborg'],
    releaseDate: '2016-12-07',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Cassiopeia',
    lanes: ['Top', 'Middle'],
    regions: ['Noxus', 'Shurima'],
    species: ['Human', 'Magically Altered'],
    releaseDate: '2010-12-14',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: "Cho'Gath",
    lanes: ['Top'],
    regions: ['Void'],
    species: ['Void-Being'],
    releaseDate: '2009-06-26',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Corki',
    lanes: ['Middle', 'Bottom'],
    regions: ['Bandle City', 'Piltover'],
    species: ['Yordle'],
    releaseDate: '2009-09-19',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Darius',
    lanes: ['Top'],
    regions: ['Noxus'],
    species: ['Human'],
    releaseDate: '2012-05-23',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Diana',
    lanes: ['Jungle', 'Middle'],
    regions: ['Targon'],
    species: ['Human', 'Aspect'],
    releaseDate: '2012-08-07',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Dr. Mundo',
    lanes: ['Top'],
    regions: ['Zaun'],
    species: ['Human', 'Chemically Altered'],
    releaseDate: '2009-09-02',
    resource: 'Health costs',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Draven',
    lanes: ['Bottom'],
    regions: ['Noxus'],
    species: ['Human'],
    releaseDate: '2012-06-06',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Ekko',
    lanes: ['Jungle', 'Middle'],
    regions: ['Zaun'],
    species: ['Human'],
    releaseDate: '2015-05-29',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Elise',
    lanes: ['Jungle'],
    regions: ['Shadow Isles', 'Noxus'],
    species: ['Human', 'Magically Altered'],
    releaseDate: '2012-10-26',
    resource: 'Mana',
    rangeTypes: ['Melee', 'Ranged'],
  },
  {
    name: 'Evelynn',
    lanes: ['Jungle'],
    regions: ['Runeterra'],
    species: ['Demon', 'Spirit'],
    releaseDate: '2009-05-01',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Ezreal',
    lanes: ['Bottom'],
    regions: ['Piltover'],
    species: ['Human', 'Magicborn'],
    releaseDate: '2010-03-16',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Fiddlesticks',
    lanes: ['Jungle'],
    regions: ['Runeterra'],
    species: ['Demon', 'Spirit'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Fiora',
    lanes: ['Top'],
    regions: ['Demacia'],
    species: ['Human'],
    releaseDate: '2012-02-29',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Fizz',
    lanes: ['Middle'],
    regions: ['Bilgewater'],
    species: ['Yordle'],
    releaseDate: '2011-11-15',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Galio',
    lanes: ['Middle'],
    regions: ['Demacia'],
    species: ['Golem'],
    releaseDate: '2010-08-10',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Gangplank',
    lanes: ['Top'],
    regions: ['Bilgewater'],
    species: ['Human'],
    releaseDate: '2009-08-19',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Garen',
    lanes: ['Top'],
    regions: ['Demacia'],
    species: ['Human'],
    releaseDate: '2010-04-27',
    resource: 'Manaless',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Gnar',
    lanes: ['Top'],
    regions: ['Freljord'],
    species: ['Yordle'],
    releaseDate: '2014-08-14',
    resource: 'Rage',
    rangeTypes: ['Melee', 'Ranged'],
  },
  {
    name: 'Gragas',
    lanes: ['Top', 'Jungle'],
    regions: ['Freljord'],
    species: ['Human', 'Iceborn'],
    releaseDate: '2010-02-02',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Graves',
    lanes: ['Jungle'],
    regions: ['Bilgewater'],
    species: ['Human'],
    releaseDate: '2011-10-19',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Gwen',
    lanes: ['Top'],
    regions: ['Shadow Isles', 'Camavor'],
    species: ['Human', 'Magically Altered'],
    releaseDate: '2021-04-15',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Hecarim',
    lanes: ['Jungle'],
    regions: ['Shadow Isles', 'Camavor'],
    species: ['Undead'],
    releaseDate: '2012-04-18',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Hwei',
    lanes: ['Middle', 'Support'],
    regions: ['Ionia'],
    species: ['Human', 'Magicborn'],
    releaseDate: '2023-12-05',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Heimerdinger',
    lanes: ['Top', 'Middle'],
    regions: ['Piltover'],
    species: ['Yordle'],
    releaseDate: '2009-10-10',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Illaoi',
    lanes: ['Top'],
    regions: ['Bilgewater'],
    species: ['Human', 'Spiritualist'],
    releaseDate: '2015-11-24',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Irelia',
    lanes: ['Top', 'Middle'],
    regions: ['Ionia'],
    species: ['Human', 'Spiritualist'],
    releaseDate: '2010-11-16',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Ivern',
    lanes: ['Jungle'],
    regions: ['Ionia', 'Freljord'],
    species: ['Human', 'Magically Altered'],
    releaseDate: '2016-10-05',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Janna',
    lanes: ['Support'],
    regions: ['Zaun', 'Shurima'],
    species: ['Spirit', 'God'],
    releaseDate: '2009-09-02',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Jarvan IV',
    lanes: ['Jungle'],
    regions: ['Demacia'],
    species: ['Human'],
    releaseDate: '2011-03-01',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Jax',
    lanes: ['Top', 'Jungle'],
    regions: ['Runeterra', 'Icathia', 'Shurima'],
    species: ['Unknown'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Jayce',
    lanes: ['Top', 'Middle'],
    regions: ['Piltover'],
    species: ['Human'],
    releaseDate: '2012-07-07',
    resource: 'Mana',
    rangeTypes: ['Melee', 'Ranged'],
  },
  {
    name: 'Jhin',
    lanes: ['Bottom'],
    regions: ['Ionia'],
    species: ['Human', 'Spiritualist'],
    releaseDate: '2016-02-01',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Jinx',
    lanes: ['Bottom'],
    regions: ['Zaun'],
    species: ['Human', 'Chemically Altered'],
    releaseDate: '2013-10-10',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: "K'Sante",
    lanes: ['Top'],
    regions: ['Shurima'],
    species: ['Human'],
    releaseDate: '2022-11-02',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: "Kai'Sa",
    lanes: ['Bottom'],
    regions: ['Shurima', 'Void'],
    species: ['Human', 'Void-Being'],
    releaseDate: '2018-03-07',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Kalista',
    lanes: ['Bottom'],
    regions: ['Shadow Isles', 'Camavor'],
    species: ['Undead'],
    releaseDate: '2014-11-20',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Karma',
    lanes: ['Support'],
    regions: ['Ionia'],
    species: ['Human', 'Spiritualist'],
    releaseDate: '2011-02-01',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Karthus',
    lanes: ['Jungle'],
    regions: ['Shadow Isles', 'Noxus'],
    species: ['Undead'],
    releaseDate: '2009-06-12',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Kassadin',
    lanes: ['Middle'],
    regions: ['Shurima', 'Void'],
    species: ['Human', 'Void-Being'],
    releaseDate: '2009-08-07',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Katarina',
    lanes: ['Middle'],
    regions: ['Noxus'],
    species: ['Human'],
    releaseDate: '2009-09-19',
    resource: 'Manaless',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Kayle',
    lanes: ['Top'],
    regions: ['Demacia', 'Targon'],
    species: ['Human', 'Magically Altered', 'Aspect'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Melee', 'Ranged'],
  },
  {
    name: 'Kayn',
    lanes: ['Jungle'],
    regions: ['Ionia', 'Runeterra', 'Noxus', 'Shurima'],
    species: ['Darkin', 'Human', 'Magically Altered'],
    releaseDate: '2017-07-12',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Kennen',
    lanes: ['Top'],
    regions: ['Ionia'],
    species: ['Yordle'],
    releaseDate: '2010-04-08',
    resource: 'Energy',
    rangeTypes: ['Ranged'],
  },
  {
    name: "Kha'Zix",
    lanes: ['Jungle'],
    regions: ['Void'],
    species: ['Void-Being'],
    releaseDate: '2012-09-27',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Kindred',
    lanes: ['Jungle'],
    regions: ['Runeterra'],
    species: ['Spirit', 'God'],
    releaseDate: '2015-10-14',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Kled',
    lanes: ['Top'],
    regions: ['Noxus'],
    species: ['Yordle'],
    releaseDate: '2016-08-10',
    resource: 'Courage',
    rangeTypes: ['Melee'],
  },
  {
    name: "Kog'Maw",
    lanes: ['Bottom'],
    regions: ['Void'],
    species: ['Void-Being'],
    releaseDate: '2010-06-24',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'LeBlanc',
    lanes: ['Middle'],
    regions: ['Noxus'],
    species: ['Human', 'Magically Altered'],
    releaseDate: '2010-11-02',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Lee Sin',
    lanes: ['Jungle'],
    regions: ['Ionia'],
    species: ['Human', 'Spiritualist'],
    releaseDate: '2011-04-01',
    resource: 'Energy',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Leona',
    lanes: ['Support'],
    regions: ['Targon'],
    species: ['Human', 'Aspect'],
    releaseDate: '2011-07-13',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Lillia',
    lanes: ['Jungle'],
    regions: ['Ionia'],
    species: ['Spirit'],
    releaseDate: '2020-07-22',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Lissandra',
    lanes: ['Middle'],
    regions: ['Freljord'],
    species: ['Human', 'Iceborn'],
    releaseDate: '2013-04-30',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Lucian',
    lanes: ['Bottom'],
    regions: ['Demacia', 'Shadow Isles'],
    species: ['Human'],
    releaseDate: '2013-08-22',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Lulu',
    lanes: ['Support'],
    regions: ['Bandle City'],
    species: ['Yordle'],
    releaseDate: '2012-03-20',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Lux',
    lanes: ['Middle', 'Support'],
    regions: ['Demacia'],
    species: ['Human', 'Magicborn'],
    releaseDate: '2010-10-19',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Malphite',
    lanes: ['Top', 'Middle'],
    regions: ['Ixtal', 'Shurima'],
    species: ['Golem'],
    releaseDate: '2009-09-02',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Malzahar',
    lanes: ['Middle'],
    regions: ['Shurima', 'Void'],
    species: ['Human', 'Void-Being'],
    releaseDate: '2010-06-01',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Maokai',
    lanes: ['Support'],
    regions: ['Shadow Isles'],
    species: ['Spirit'],
    releaseDate: '2011-02-16',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Master Yi',
    lanes: ['Jungle'],
    regions: ['Ionia'],
    species: ['Human', 'Spiritualist'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Milio',
    lanes: ['Support'],
    regions: ['Ixtal'],
    species: ['Human', 'Magicborn'],
    releaseDate: '2023-03-23',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Miss Fortune',
    lanes: ['Bottom'],
    regions: ['Bilgewater'],
    species: ['Human'],
    releaseDate: '2010-09-08',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Mordekaiser',
    lanes: ['Top'],
    regions: ['Noxus', 'Shadow Isles'],
    species: ['Revenant'],
    releaseDate: '2010-02-24',
    resource: 'Shield',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Morgana',
    lanes: ['Support'],
    regions: ['Demacia', 'Targon'],
    species: ['Human', 'Magically Altered', 'Aspect'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Naafiri',
    lanes: ['Middle'],
    regions: ['Shurima'],
    species: ['Dog', 'Darkin'],
    releaseDate: '2023-07-19',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Nami',
    lanes: ['Support'],
    regions: ['Runeterra', 'Bilgewater'],
    species: ['Vastayan'],
    releaseDate: '2012-12-07',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Nasus',
    lanes: ['Top'],
    regions: ['Shurima'],
    species: ['God-Warrior'],
    releaseDate: '2009-10-01',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Nautilus',
    lanes: ['Support'],
    regions: ['Bilgewater'],
    species: ['Revenant'],
    releaseDate: '2012-02-14',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Neeko',
    lanes: ['Middle', 'Support'],
    regions: ['Ixtal'],
    species: ['Vastayan'],
    releaseDate: '2018-12-05',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Nidalee',
    lanes: ['Jungle'],
    regions: ['Ixtal'],
    species: ['Human', 'Spiritualist'],
    releaseDate: '2009-12-17',
    resource: 'Mana',
    rangeTypes: ['Melee', 'Ranged'],
  },
  {
    name: 'Nilah',
    lanes: ['Bottom'],
    regions: ['Bilgewater'],
    species: ['Human', 'Magically Altered'],
    releaseDate: '2022-07-13',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Nocturne',
    lanes: ['Jungle'],
    regions: ['Runeterra'],
    species: ['Demon', 'Spirit'],
    releaseDate: '2011-03-15',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Nunu & Willump',
    lanes: ['Jungle'],
    regions: ['Freljord'],
    species: ['Human', 'Yeti'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Olaf',
    lanes: ['Top'],
    regions: ['Freljord'],
    species: ['Human', 'Iceborn'],
    releaseDate: '2010-06-09',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Orianna',
    lanes: ['Middle'],
    regions: ['Piltover'],
    species: ['Golem'],
    releaseDate: '2011-06-01',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Ornn',
    lanes: ['Top'],
    regions: ['Freljord'],
    species: ['Spirit', 'God'],
    releaseDate: '2017-08-23',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Pantheon',
    lanes: ['Top', 'Support'],
    regions: ['Targon'],
    species: ['Human', 'Aspect'],
    releaseDate: '2010-02-02',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Poppy',
    lanes: ['Top', 'Jungle', 'Support'],
    regions: ['Demacia'],
    species: ['Yordle'],
    releaseDate: '2010-01-13',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Pyke',
    lanes: ['Support'],
    regions: ['Bilgewater'],
    species: ['Revenant'],
    releaseDate: '2018-05-31',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Qiyana',
    lanes: ['Middle'],
    regions: ['Ixtal'],
    species: ['Human', 'Magicborn'],
    releaseDate: '2019-06-28',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Quinn',
    lanes: ['Top'],
    regions: ['Demacia'],
    species: ['Human'],
    releaseDate: '2013-03-01',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Rakan',
    lanes: ['Support'],
    regions: ['Ionia'],
    species: ['Vastayan'],
    releaseDate: '2017-04-19',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Rammus',
    lanes: ['Jungle'],
    regions: ['Shurima'],
    species: ['Unknown'],
    releaseDate: '2009-07-10',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: "Rek'Sai",
    lanes: ['Jungle'],
    regions: ['Shurima', 'Void'],
    species: ['Void-Being'],
    releaseDate: '2014-12-11',
    resource: 'Rage',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Rell',
    lanes: ['Support'],
    regions: ['Noxus'],
    species: ['Human', 'Magicborn', 'Magically Altered'],
    releaseDate: '2020-12-10',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Renata Glasc',
    lanes: ['Support'],
    regions: ['Zaun'],
    species: ['Human', 'Chemically Altered'],
    releaseDate: '2022-02-17',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Renekton',
    lanes: ['Top'],
    regions: ['Shurima'],
    species: ['God-Warrior'],
    releaseDate: '2011-01-18',
    resource: 'Fury',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Rengar',
    lanes: ['Jungle'],
    regions: ['Ixtal', 'Shurima'],
    species: ['Vastayan'],
    releaseDate: '2012-08-21',
    resource: 'Ferocity',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Riven',
    lanes: ['Top'],
    regions: ['Ionia', 'Noxus'],
    species: ['Human'],
    releaseDate: '2011-09-14',
    resource: 'Manaless',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Rumble',
    lanes: ['Top'],
    regions: ['Bandle City'],
    species: ['Yordle'],
    releaseDate: '2011-04-26',
    resource: 'Heat',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Ryze',
    lanes: ['Top', 'Middle'],
    regions: ['Runeterra'],
    species: ['Human', 'Magically Altered'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Samira',
    lanes: ['Bottom'],
    regions: ['Shurima', 'Noxus'],
    species: ['Human'],
    releaseDate: '2020-09-21',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Sejuani',
    lanes: ['Jungle'],
    regions: ['Freljord'],
    species: ['Human', 'Iceborn'],
    releaseDate: '2012-01-17',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Senna',
    lanes: ['Support'],
    regions: ['Shadow Isles'],
    species: ['Human', 'Undead'],
    releaseDate: '2019-11-10',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Seraphine',
    lanes: ['Support'],
    regions: ['Piltover', 'Zaun'],
    species: ['Human', 'Magicborn'],
    releaseDate: '2020-10-29',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Sett',
    lanes: ['Top'],
    regions: ['Ionia'],
    species: ['Human', 'Vastayan'],
    releaseDate: '2020-01-14',
    resource: 'Grit',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Shaco',
    lanes: ['Jungle'],
    regions: ['Runeterra'],
    species: ['Spirit'],
    releaseDate: '2009-10-10',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Shen',
    lanes: ['Top', 'Support'],
    regions: ['Ionia'],
    species: ['Human', 'Spiritualist'],
    releaseDate: '2010-03-24',
    resource: 'Energy',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Shyvana',
    lanes: ['Jungle'],
    regions: ['Demacia'],
    species: ['Dragon', 'Magically Altered'],
    releaseDate: '2011-11-01',
    resource: 'Fury',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Singed',
    lanes: ['Top'],
    regions: ['Zaun', 'Piltover'],
    species: ['Human', 'Chemically Altered'],
    releaseDate: '2009-04-18',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Sion',
    lanes: ['Top'],
    regions: ['Noxus'],
    species: ['Revenant'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Sivir',
    lanes: ['Bottom'],
    regions: ['Shurima'],
    species: ['Human'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Skarner',
    lanes: ['Top', 'Jungle'],
    regions: ['Ixtal'],
    species: ['Brackern'],
    releaseDate: '2011-08-09',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Smolder',
    lanes: ['Bottom'],
    regions: ['Camavor', 'Noxus'],
    species: ['Dragon'],
    releaseDate: '2024-01-31',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Sona',
    lanes: ['Support'],
    regions: ['Demacia', 'Ionia'],
    species: ['Human', 'Magicborn'],
    releaseDate: '2010-09-21',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Soraka',
    lanes: ['Support'],
    regions: ['Targon', 'Ionia'],
    species: ['Celestial'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Swain',
    lanes: ['Support'],
    regions: ['Noxus'],
    species: ['Human', 'Magically Altered'],
    releaseDate: '2010-10-05',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Sylas',
    lanes: ['Jungle', 'Middle'],
    regions: ['Demacia', 'Freljord'],
    species: ['Human', 'Magicborn'],
    releaseDate: '2019-01-25',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Syndra',
    lanes: ['Middle'],
    regions: ['Ionia'],
    species: ['Human', 'Magicborn'],
    releaseDate: '2012-09-13',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Tahm Kench',
    lanes: ['Top', 'Support'],
    regions: ['Bilgewater', 'Runeterra'],
    species: ['Demon', 'Spirit'],
    releaseDate: '2015-07-09',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Taliyah',
    lanes: ['Jungle', 'Middle'],
    regions: ['Shurima'],
    species: ['Human', 'Magicborn'],
    releaseDate: '2016-05-18',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Talon',
    lanes: ['Jungle', 'Middle'],
    regions: ['Noxus'],
    species: ['Human'],
    releaseDate: '2011-08-24',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Taric',
    lanes: ['Support'],
    regions: ['Targon', 'Demacia'],
    species: ['Human', 'Aspect'],
    releaseDate: '2009-08-19',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Teemo',
    lanes: ['Top'],
    regions: ['Bandle City'],
    species: ['Yordle'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Thresh',
    lanes: ['Support'],
    regions: ['Shadow Isles'],
    species: ['Undead'],
    releaseDate: '2013-01-23',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Tristana',
    lanes: ['Middle', 'Bottom'],
    regions: ['Bandle City'],
    species: ['Yordle'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Trundle',
    lanes: ['Top', 'Jungle'],
    regions: ['Freljord'],
    species: ['Troll', 'Iceborn'],
    releaseDate: '2010-12-01',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Tryndamere',
    lanes: ['Top'],
    regions: ['Freljord'],
    species: ['Human', 'Magically Altered'],
    releaseDate: '2009-05-01',
    resource: 'Fury',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Twisted Fate',
    lanes: ['Top', 'Middle'],
    regions: ['Bilgewater'],
    species: ['Human', 'Magicborn'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Twitch',
    lanes: ['Bottom'],
    regions: ['Zaun'],
    species: ['Rat', 'Chemically Altered'],
    releaseDate: '2009-05-01',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Udyr',
    lanes: ['Jungle'],
    regions: ['Freljord', 'Ionia'],
    species: ['Human', 'Spiritualist'],
    releaseDate: '2009-12-02',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Urgot',
    lanes: ['Top'],
    regions: ['Noxus', 'Zaun'],
    species: ['Human', 'Chemically Altered', 'Cyborg'],
    releaseDate: '2010-08-24',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Varus',
    lanes: ['Bottom'],
    regions: ['Ionia', 'Runeterra', 'Shurima'],
    species: ['Darkin', 'Human'],
    releaseDate: '2012-05-08',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Vayne',
    lanes: ['Top', 'Bottom'],
    regions: ['Demacia'],
    species: ['Human'],
    releaseDate: '2011-05-10',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Veigar',
    lanes: ['Middle'],
    regions: ['Runeterra', 'Bandle City', 'Shadow Isles'],
    species: ['Yordle'],
    releaseDate: '2009-07-24',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: "Vel'Koz",
    lanes: ['Middle', 'Support'],
    regions: ['Void'],
    species: ['Void-Being'],
    releaseDate: '2014-02-27',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Vex',
    lanes: ['Middle'],
    regions: ['Shadow Isles', 'Bandle City'],
    species: ['Yordle'],
    releaseDate: '2021-09-23',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Vi',
    lanes: ['Jungle'],
    regions: ['Piltover', 'Zaun'],
    species: ['Human'],
    releaseDate: '2012-12-19',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Viego',
    lanes: ['Jungle'],
    regions: ['Shadow Isles', 'Camavor'],
    species: ['Undead'],
    releaseDate: '2021-01-21',
    resource: 'Manaless',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Viktor',
    lanes: ['Middle'],
    regions: ['Piltover', 'Zaun'],
    species: ['Human', 'Cyborg'],
    releaseDate: '2011-12-29',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Vladimir',
    lanes: ['Top', 'Middle'],
    regions: ['Noxus', 'Shadow Isles', 'Camavor'],
    species: ['Human', 'Magically Altered'],
    releaseDate: '2010-07-27',
    resource: 'Bloodthirst',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Volibear',
    lanes: ['Top', 'Jungle'],
    regions: ['Freljord'],
    species: ['Spirit', 'God'],
    releaseDate: '2011-11-29',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Warwick',
    lanes: ['Top', 'Jungle'],
    regions: ['Zaun'],
    species: ['Human', 'Chemically Altered', 'Cyborg'],
    releaseDate: '2009-02-21',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Wukong',
    lanes: ['Top', 'Jungle'],
    regions: ['Ionia'],
    species: ['Vastayan'],
    releaseDate: '2011-07-26',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Xayah',
    lanes: ['Bottom'],
    regions: ['Ionia'],
    species: ['Vastayan'],
    releaseDate: '2017-04-19',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Xerath',
    lanes: ['Middle', 'Support'],
    regions: ['Shurima'],
    species: ['God-Warrior'],
    releaseDate: '2011-10-05',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Xin Zhao',
    lanes: ['Jungle'],
    regions: ['Demacia', 'Ionia', 'Noxus'],
    species: ['Human'],
    releaseDate: '2010-07-13',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Yasuo',
    lanes: ['Middle'],
    regions: ['Ionia'],
    species: ['Human', 'Magicborn'],
    releaseDate: '2013-12-13',
    resource: 'Flow',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Yone',
    lanes: ['Top', 'Middle'],
    regions: ['Ionia'],
    species: ['Human', 'Magically Altered'],
    releaseDate: '2020-08-06',
    resource: 'Manaless',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Yorick',
    lanes: ['Top'],
    regions: ['Shadow Isles'],
    species: ['Human', 'Magically Altered'],
    releaseDate: '2011-06-22',
    resource: 'Mana',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Yuumi',
    lanes: ['Support'],
    regions: ['Bandle City'],
    species: ['Cat', 'Magically Altered'],
    releaseDate: '2019-05-14',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Zac',
    lanes: ['Top', 'Jungle'],
    regions: ['Zaun'],
    species: ['Golem'],
    releaseDate: '2013-03-29',
    resource: 'Health costs',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Zed',
    lanes: ['Middle'],
    regions: ['Ionia'],
    species: ['Human', 'Magically Altered'],
    releaseDate: '2012-11-13',
    resource: 'Energy',
    rangeTypes: ['Melee'],
  },
  {
    name: 'Zeri',
    lanes: ['Bottom'],
    regions: ['Zaun'],
    species: ['Human', 'Magicborn'],
    releaseDate: '2022-01-20',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Ziggs',
    lanes: ['Middle', 'Bottom'],
    regions: ['Zaun'],
    species: ['Yordle'],
    releaseDate: '2012-02-01',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Zilean',
    lanes: ['Support'],
    regions: ['Runeterra', 'Icathia', 'Shurima'],
    species: ['Human', 'Magicborn'],
    releaseDate: '2009-04-18',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Zoe',
    lanes: ['Middle'],
    regions: ['Targon'],
    species: ['Human', 'Aspect'],
    releaseDate: '2017-11-21',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
  {
    name: 'Zyra',
    lanes: ['Support'],
    regions: ['Ixtal'],
    species: ['Unknown'],
    releaseDate: '2012-07-24',
    resource: 'Mana',
    rangeTypes: ['Ranged'],
  },
] as Champion[];
